In [1]:
import os
import numpy as np
import pandas as pd
import nibabel as nib
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision.transforms.functional import resize
from torchvision.transforms import InterpolationMode
import random
import time

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [ ]:
os.chdir('/home/ntdung/Medical')

In [3]:
os.chdir('/media/sslab/PACS/sslab/nguyentiendung')

In [4]:
excel_path = 'data/participants_1.xlsx'
df = pd.read_excel(excel_path, nrows=None)
df

,No.,subject_age,subject_dx,subject_sex,subject_id,dataset_name
0,1,44.2,control,m,sub-BrainAge000019,ABIDE/Caltech
1,2,39.3,control,m,sub-BrainAge000020,ABIDE/Caltech
2,3,42.5,control,m,sub-BrainAge000021,ABIDE/Caltech
3,4,19.7,control,m,sub-BrainAge000022,ABIDE/Caltech
4,5,20.0,control,f,sub-BrainAge000023,ABIDE/Caltech
...,...,...,...,...,...,...
4919,4944,66.0,control,f,sub-BrainAge023209,RocklandSample
4920,4945,69.0,control,m,sub-BrainAge023210,RocklandSample
4921,4946,23.0,control,m,sub-BrainAge023211,RocklandSample
4922,4947,54.0,control,f,sub-BrainAge023212,RocklandSample
4923,4948,75.0,control,f,sub-BrainAge023213,RocklandSample

In [5]:
def is_integer(n):
    return float(n).is_integer()

n_total = len(df)
n_integer = df['subject_age'].apply(is_integer).sum()
n_decimal = n_total - n_integer

print(f"Samples with integer age values: {n_integer}")
print(f"Samples with decimal age values: {n_decimal}")

Samples with integer age values: 4218
Samples with decimal age values: 706

In [6]:
df['subject_age'] = df['subject_age'].round().astype(int)
df

,No.,subject_age,subject_dx,subject_sex,subject_id,dataset_name
0,1,44,control,m,sub-BrainAge000019,ABIDE/Caltech
1,2,39,control,m,sub-BrainAge000020,ABIDE/Caltech
2,3,42,control,m,sub-BrainAge000021,ABIDE/Caltech
3,4,20,control,m,sub-BrainAge000022,ABIDE/Caltech
4,5,20,control,f,sub-BrainAge000023,ABIDE/Caltech
...,...,...,...,...,...,...
4919,4944,66,control,f,sub-BrainAge023209,RocklandSample
4920,4945,69,control,m,sub-BrainAge023210,RocklandSample
4921,4946,23,control,m,sub-BrainAge023211,RocklandSample
4922,4947,54,control,f,sub-BrainAge023212,RocklandSample
4923,4948,75,control,f,sub-BrainAge023213,RocklandSample

# Prepare Input

In [7]:
class BrainMRIDataset(Dataset):
    """
    Dataset cho Brain MRI với thông tin tuổi và giới tính thật và phản thực
    """
    def __init__(self, data_dir, participants_file, transform=None, img_size=128):
        self.data_dir = data_dir
        self.transform = transform
        self.img_size = img_size

        self.participants_df = pd.read_excel(participants_file)
        self.participants_df['subject_age'] = self.participants_df['subject_age'].round().astype(int)
        
        # Chuẩn hóa giới tính thành giá trị số
        self.participants_df['gender_code'] = self.participants_df['subject_sex'].map({'m': 0, 'f': 1})
        
        # Chuẩn hóa tuổi (min-max scaling)
        self.min_age = self.participants_df['subject_age'].min()
        self.max_age = self.participants_df['subject_age'].max()
        self.age_range = self.max_age - self.min_age
        
        # Lọc các mẫu có dữ liệu MRI hợp lệ
        valid_subjects = []
        for subject_id in self.participants_df['subject_id']:
            file_path = os.path.join(data_dir, subject_id, 'anat', f"{subject_id}_T1w.nii.gz")
            if os.path.exists(file_path):
                valid_subjects.append(subject_id)
        
        self.participants_df = self.participants_df[self.participants_df['subject_id'].isin(valid_subjects)]
        print(f"Found {len(self.participants_df)} samples with valid MRI data")
    
    def __len__(self):
        return len(self.participants_df)
    
    def _get_middle_slices(self, subject_id):
        try:
            file_path = os.path.join(self.data_dir, subject_id, 'anat', f"{subject_id}_T1w.nii.gz")
            img = nib.load(file_path)
            img_data = img.get_fdata()
            
            # Lấy 3 lát cắt giữa
            slices = [
                img_data[:, :, img_data.shape[2]//2],  # axial
                img_data[img_data.shape[0]//2, :, :],  # sagittal
                img_data[:, img_data.shape[1]//2, :]   # coronal
            ]
            
            ## Chuyển đổi sang tensor và chuẩn hóa
            processed_slices = []
            for slice_data in slices:
                tensor_slice = torch.from_numpy(slice_data).float()
                # Min-max normalization
                if tensor_slice.max() > tensor_slice.min():  # Tránh chia cho 0
                    tensor_slice = (tensor_slice - tensor_slice.min()) / (tensor_slice.max() - tensor_slice.min())
                    
                # Resize slice về kích thước cố định (128x128)
                tensor_slice = tensor_slice.unsqueeze(0)  # Thêm chiều kênh [1, H, W]
                resized_slice = F.interpolate(
                    tensor_slice.unsqueeze(0),  # Thêm chiều batch [1, 1, H, W]
                    size=(self.img_size, self.img_size),
                    mode='bilinear',
                    align_corners=False
                ).squeeze(0)  # Loại bỏ chiều batch [1, H, W]
                
                if self.transform:
                    resized_slice = self.transform(resized_slice)

                processed_slices.append(resized_slice)
            
            # Ghép các lát cắt thành một tensor [3, H, W]
            return torch.cat(processed_slices, dim=0)
            
        except Exception as e:
            print(f"Error when processing {subject_id}: {e}")
            # Trả về tensor 0 trong trường hợp lỗi
            return torch.zeros((3, 130, 130), dtype=torch.float32)
    
    def normalize_age(self, age):
        """Chuẩn hóa tuổi về khoảng [0, 1]"""
        return (age - self.min_age) / self.age_range if self.age_range > 0 else 0
    
    def __getitem__(self, idx):
        """
        Lấy một mẫu từ dataset
        """
        # Lấy thông tin mẫu thật
        real_info = self.participants_df.iloc[idx]
        real_id = real_info['subject_id']
        real_age = real_info['subject_age']
        real_gender = real_info['gender_code']
        
        # Lấy thông tin phản thực từ một mẫu ngẫu nhiên khác
        valid_indices = [i for i in range(len(self)) if i != idx]
        if not valid_indices:  # Nếu chỉ có 1 mẫu trong dataset
            cf_info = real_info
        else:
            cf_idx = random.choice(valid_indices)
            cf_info = self.participants_df.iloc[cf_idx]
        
        cf_id = cf_info['subject_id']
        cf_age = cf_info['subject_age']
        cf_gender = cf_info['gender_code']

        # Lấy ảnh và chuẩn hóa điều kiện
        real_img = self._get_middle_slices(real_id)
        
        # Chuẩn bị điều kiện
        real_condition = torch.tensor([self.normalize_age(real_age), real_gender], dtype=torch.float32)
        cf_condition = torch.tensor([self.normalize_age(cf_age), cf_gender], dtype=torch.float32)
        
        # Cũng chuẩn bị điều kiện gốc (không chuẩn hóa) cho việc kiểm tra/ghi log
        real_raw_condition = torch.tensor([real_age, real_gender], dtype=torch.float32)
        cf_raw_condition = torch.tensor([cf_age, cf_gender], dtype=torch.float32)
        
        return {
            'real_id': real_id,
            'cf_id': cf_id,
            'real_img': real_img,  # Shape: [3, H, W]
            'real_condition': real_condition,  # Shape: [2] - chuẩn hóa
            'cf_condition': cf_condition,  # Shape: [2] - chuẩn hóa
            'real_raw_condition': real_raw_condition,  # Shape: [2] - không chuẩn hóa
            'cf_raw_condition': cf_raw_condition  # Shape: [2] - không chuẩn hóa
        }

In [8]:
dataset = BrainMRIDataset(data_dir='data', participants_file='data/participants_1.xlsx')
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

Found 4924 samples with valid MRI data

In [9]:
sample = dataset[0]

print("Real ID:", sample['real_id'])
print("Counterfactual ID:", sample['cf_id'])
print("Real image shape:", sample['real_img'].shape)
print("Real condition (normalized):", sample['real_condition'])
print("Counterfactual condition (normalized):", sample['cf_condition'])
print("Real condition (raw):", sample['real_raw_condition'])
print("Counterfactual condition (raw):", sample['cf_raw_condition'])

Real ID: sub-BrainAge000019
Counterfactual ID: sub-BrainAge019166
Real image shape: torch.Size([3, 128, 128])
Real condition (normalized): tensor([0.3291, 0.0000])
Counterfactual condition (normalized): tensor([0.0759, 1.0000])
Real condition (raw): tensor([44.,  0.])
Counterfactual condition (raw): tensor([24.,  1.])

In [10]:
batch = next(iter(dataloader))

print("Real image batch shape:", batch['real_img'].shape)
print("Real condition (normalized):", batch['real_condition'], batch['real_condition'].shape)
print("Counterfactual condition (normalized):", batch['cf_condition'], batch['cf_condition'].shape)
print("Real IDs:", batch['real_id'])
print("Counterfactual IDs:", batch['cf_id'])

Real image batch shape: torch.Size([4, 3, 128, 128])
Real condition (normalized): tensor([[0.0759, 1.0000],
        [0.3797, 1.0000],
        [0.5696, 1.0000],
        [0.5316, 1.0000]]) torch.Size([4, 2])
Counterfactual condition (normalized): tensor([[0.5316, 0.0000],
        [0.4937, 1.0000],
        [0.0253, 1.0000],
        [0.6329, 1.0000]]) torch.Size([4, 2])
Real IDs: ['sub-BrainAge011248', 'sub-BrainAge005592', 'sub-BrainAge005925', 'sub-BrainAge019156']
Counterfactual IDs: ['sub-BrainAge018834', 'sub-BrainAge020114', 'sub-BrainAge019520', 'sub-BrainAge021141']

# Generator

In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class ConvBlock(nn.Module):
    """Khối tích chập cơ bản cho U-Net"""
    def __init__(self, in_channels, out_channels):
        super(ConvBlock, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )
        
    def forward(self, x):
        return self.conv(x)

class SpatialTransformer(nn.Module):
    """Lớp biến đổi không gian để áp dụng biến dạng vào ảnh"""
    def __init__(self):
        super(SpatialTransformer, self).__init__()
    
    def forward(self, src, flow):
        """
        src: tensor hình ảnh nguồn [B, C, H, W]
        flow: tensor trường vector biến dạng [B, 2, H, W]
        """
        # Tạo lưới tọa độ chuẩn
        B, C, H, W = src.size()
        
        # Tạo lưới tọa độ chuẩn (từ -1 đến 1)
        grid_y, grid_x = torch.meshgrid(
            torch.linspace(-1, 1, H, device=src.device),
            torch.linspace(-1, 1, W, device=src.device),
            indexing='ij'  # Thêm indexing='ij' để tương thích với PyTorch mới
        )
        grid = torch.stack((grid_x, grid_y), dim=2).unsqueeze(0)
        grid = grid.expand(B, H, W, 2)
        
        # Chuyển đổi flow từ pixel sang giá trị chuẩn hóa (-1 đến 1)
        flow_grid = flow.permute(0, 2, 3, 1)  # [B, H, W, 2]
        flow_grid = flow_grid / torch.tensor([W/2, H/2], device=flow.device)
        
        # Cộng flow vào lưới cơ sở để tạo ra lưới biến dạng
        sample_grid = grid + flow_grid
        
        # Áp dụng lưới biến dạng để lấy mẫu từ ảnh gốc
        output = F.grid_sample(src, sample_grid, mode='bilinear', padding_mode='border', align_corners=True)
        
        return output

class ScalingAndSquaring(nn.Module):
    """Lớp scaling and squaring để tích hợp trường vận tốc thành trường biến dạng"""
    def __init__(self, n_steps=7):
        super(ScalingAndSquaring, self).__init__()
        self.n_steps = n_steps
        self.transformer = SpatialTransformer()
        
    def forward(self, velocity):
        """
        velocity: tensor trường vận tốc [B, 2, H, W]
        return: trường biến dạng phi(x) thông qua tích hợp scaling and squaring
        """
        # Chia nhỏ trường vận tốc
        flow = velocity / (2 ** self.n_steps)
        
        # Thực hiện scaling and squaring
        for _ in range(self.n_steps):
            flow = flow + self.transformer(flow, flow)
            
        return flow

class Generator(nn.Module):
    """Generator U-Net với scaling and squaring layers"""
    def __init__(self, in_channels=5, init_features=16):
        """
        in_channels: số kênh đầu vào (3 cho ảnh + 2 cho điều kiện)
        """
        super(Generator, self).__init__()
        
        # Encoder
        self.encoder1 = ConvBlock(in_channels, init_features)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        self.encoder2 = ConvBlock(init_features, init_features*2)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        self.encoder3 = ConvBlock(init_features*2, init_features*2)
        self.pool3 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        # Bridge
        self.bridge = ConvBlock(init_features*2, init_features*2)
        
        # Decoder - Sử dụng Upsample thay vì ConvTranspose2d
        self.upconv3 = nn.Sequential(
            nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True),
            nn.Conv2d(init_features*2, init_features*2, kernel_size=3, padding=1)
        )
        self.decoder3 = ConvBlock(init_features*4, init_features*2)
        
        self.upconv2 = nn.Sequential(
            nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True),
            nn.Conv2d(init_features*2, init_features*2, kernel_size=3, padding=1)
        )
        self.decoder2 = ConvBlock(init_features*4, init_features)
        
        self.upconv1 = nn.Sequential(
            nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True),
            nn.Conv2d(init_features, init_features, kernel_size=3, padding=1)
        )
        self.decoder1 = ConvBlock(init_features*2, init_features)
        
        # Velocity field prediction (2 kênh cho x và y)
        self.velocity = nn.Conv2d(init_features, 2, kernel_size=3, padding=1)
        
        # Scaling and squaring layer
        self.scaling_squaring = ScalingAndSquaring(n_steps=7)
        
        # Spatial transformer để áp dụng biến dạng
        self.transformer = SpatialTransformer()
        
    def forward(self, x, condition):
        """
        x: tensor ảnh đầu vào [B, 3, H, W]
        condition: tensor điều kiện mục tiêu [B, 2]
        """
        batch_size, _, H, W = x.size()
        
        # Mở rộng điều kiện thành kênh không gian
        condition = condition.view(batch_size, 2, 1, 1).expand(-1, -1, H, W)
        
        # Ghép ảnh và điều kiện
        x_in = torch.cat([x, condition], dim=1)  # [B, 5, H, W]
        
        # Encoder
        enc1 = self.encoder1(x_in)
        enc1_pool = self.pool1(enc1)
        
        enc2 = self.encoder2(enc1_pool)
        enc2_pool = self.pool2(enc2)
        
        enc3 = self.encoder3(enc2_pool)
        enc3_pool = self.pool3(enc3)
        
        # Bridge
        bridge = self.bridge(enc3_pool)
        
        # Decoder với skip connections
        up3 = self.upconv3(bridge)
        
        # Đảm bảo kích thước khớp nhau
        if up3.shape[2:] != enc3.shape[2:]:
            up3 = F.interpolate(up3, size=enc3.shape[2:], mode='bilinear', align_corners=True)
            
        up3 = torch.cat([up3, enc3], dim=1)
        dec3 = self.decoder3(up3)
        up2 = self.upconv2(dec3)
        
        # Đảm bảo kích thước khớp nhau
        if up2.shape[2:] != enc2.shape[2:]:
            up2 = F.interpolate(up2, size=enc2.shape[2:], mode='bilinear', align_corners=True)
            
        up2 = torch.cat([up2, enc2], dim=1)
        dec2 = self.decoder2(up2)
        up1 = self.upconv1(dec2)
        
        # Đảm bảo kích thước khớp nhau
        if up1.shape[2:] != enc1.shape[2:]:
            up1 = F.interpolate(up1, size=enc1.shape[2:], mode='bilinear', align_corners=True)
            
        up1 = torch.cat([up1, enc1], dim=1)
        dec1 = self.decoder1(up1)
        
        # Dự đoán trường vận tốc
        velocity = self.velocity(dec1)
        
        # Tích hợp trường vận tốc để có trường biến dạng
        flow = self.scaling_squaring(velocity)
        
        # Áp dụng trường biến dạng vào ảnh gốc
        deformed_image = self.transformer(x, flow)
        
        return deformed_image, flow

class MultiSliceGenerator(nn.Module):
    """Mô hình Generator xử lý đồng thời 3 lát cắt MRI"""
    def __init__(self):
        super(MultiSliceGenerator, self).__init__()
        # Mỗi lát cắt được xử lý bởi một generator riêng
        self.generators = nn.ModuleList([
            Generator(in_channels=3+2)  # 3 channels cho ảnh + 2 cho điều kiện
            for _ in range(3)
        ])
        
    def forward(self, x, condition):
        """
        x: tensor ảnh gốc [B, 3, H, W]
        condition: tensor điều kiện mục tiêu [B, 2]
        """
        outputs = []
        flows = []
        
        # Xử lý mỗi lát cắt riêng biệt
        for i in range(3):
            slice_img = x[:, i:i+1, :, :]  # Lấy 1 lát cắt [B, 1, H, W]
            
            # Nhân rộng lát cắt thành 3 kênh để phù hợp với đầu vào của Generator
            slice_img = slice_img.repeat(1, 3, 1, 1)  # [B, 3, H, W]
            
            # Đưa vào generator
            output, flow = self.generators[i](slice_img, condition)
            
            # Lấy kênh đầu tiên của output (vì cả 3 kênh giống nhau)
            output = output[:, 0:1, :, :]  # [B, 1, H, W]
            
            outputs.append(output)
            flows.append(flow)
        
        # Ghép 3 lát cắt đã xử lý
        generated_img = torch.cat(outputs, dim=1)  # [B, 3, H, W]
        
        return generated_img, flows

In [12]:
def test_generator():
    """Hàm kiểm tra Generator với kích thước đầu vào 128x128"""
    # Thiết lập seed cho tính khả lặp lại
    torch.manual_seed(42)
    
    # Tạo đầu vào giả
    batch_size = 2
    img_size = 128
    
    # Tạo ảnh đầu vào giả với 3 slice
    fake_img = torch.rand(batch_size, 3, img_size, img_size)
    
    # Tạo điều kiện giả (tuổi đã chuẩn hóa và giới tính)
    fake_condition = torch.tensor([[0.5, 0], [0.7, 1]], dtype=torch.float32)
    
    # Tạo mô hình
    model = MultiSliceGenerator()
    print("Mô hình MultiSliceGenerator đã được khởi tạo.")
    total_params = sum(p.numel() for p in model.parameters())
    print(f"Discriminator total parameters: {total_params:,}")

    # Chuyển sang chế độ evaluation
    model.eval()
    
    # Thực hiện forward pass
    with torch.no_grad():
        output_img, output_flows = model(fake_img, fake_condition)
    
    # In kích thước đầu ra
    print("\nKết quả:")
    print(f"Input image shape: {fake_img.shape}")
    print(f"Output image shape: {output_img.shape}")
    print(f"Number of flow fields: {len(output_flows)}")
    for i, flow in enumerate(output_flows):
        print(f"Flow {i+1} shape: {flow.shape}")
    
    return output_img, output_flows

# Chạy hàm test
if __name__ == "__main__":
    test_generator()

Mô hình MultiSliceGenerator đã được khởi tạo.
Discriminator total parameters: 365,862

Kết quả:
Input image shape: torch.Size([2, 3, 128, 128])
Output image shape: torch.Size([2, 3, 128, 128])
Number of flow fields: 3
Flow 1 shape: torch.Size([2, 2, 128, 128])
Flow 2 shape: torch.Size([2, 2, 128, 128])
Flow 3 shape: torch.Size([2, 2, 128, 128])

# Discriminator

In [13]:
def weights_init_normal(model):
    '''
    Khởi tạo trọng số ổn định hơn cho mô hình so với khởi tạo mặc định của PyTorch
    :param model: mô hình cần khởi tạo
    :return:
    '''
    classname = model.__class__.__name__
    # Chỉ áp dụng khởi tạo cho các lớp Conv2d, không phải các module tổng hợp có "Conv" trong tên
    if classname == "Conv2d":
        torch.nn.init.normal_(model.weight.data, 0.0, 0.02)
        if model.bias is not None:
            torch.nn.init.constant_(model.bias.data, 0.0)
    # Khởi tạo cho các lớp BatchNorm
    elif classname.find("BatchNorm2d") != -1:
        torch.nn.init.normal_(model.weight.data, 1.0, 0.02)
        torch.nn.init.constant_(model.bias.data, 0.0)
    # Khởi tạo cho các lớp Linear
    elif classname.find("Linear") != -1:
        torch.nn.init.normal_(model.weight.data, 0.0, 0.02)
        if model.bias is not None:
            torch.nn.init.constant_(model.bias.data, 0.0)

def conv_layer_2d(in_channel, out_channel, maxpool=True, kernel_size=3, padding=1, maxpool_stride=2):
    '''
    Tạo một block convolutional 2D gồm Conv2D, BatchNorm2D, (MaxPool2D tùy chọn), và ReLU
    '''
    if maxpool is True:
        layer = nn.Sequential(
            nn.Conv2d(in_channel, out_channel, padding=padding, kernel_size=kernel_size),
            nn.BatchNorm2d(out_channel),
            nn.MaxPool2d(2, stride=maxpool_stride),
            nn.ReLU(),
        )
    else:
        layer = nn.Sequential(
            nn.Conv2d(in_channel, out_channel, padding=padding, kernel_size=kernel_size),
            nn.BatchNorm2d(out_channel),
            nn.ReLU()
        )
    return layer

class Discriminator(nn.Module):

    def __init__(self, in_channels=3, channel_number=[16, 32, 64, 128, 256, 64]):
        '''
        Discriminator hoàn toàn convolutional cho GAN sinh ảnh phản thực
        :param in_channels: Số kênh đầu vào (3 lát cắt từ 3 trục)
        :param channel_number: Số kênh cho các lớp convolutional
        '''
        super(Discriminator, self).__init__()
        
        n_layer = len(channel_number)
        self.feature_extractor = nn.Sequential()
        
        # Xây dựng mạng trích xuất đặc trưng
        for i in range(n_layer):
            if i == 0:
                in_channel = in_channels  # Bắt đầu với số kênh đầu vào (3)
            else:
                in_channel = channel_number[i - 1]
            
            out_channel = channel_number[i]
            
            if i < n_layer - 1:
                # Sử dụng maxpool cho tất cả các lớp trừ lớp cuối
                self.feature_extractor.add_module(f'conv_{i}',
                                                  conv_layer_2d(in_channel,
                                                            out_channel,
                                                            maxpool=True,
                                                            kernel_size=3,
                                                            padding=1))
            else:
                # Lớp cuối không dùng maxpool
                self.feature_extractor.add_module(f'conv_{i}',
                                                  conv_layer_2d(in_channel,
                                                            out_channel,
                                                            maxpool=False,
                                                            kernel_size=1,
                                                            padding=0))

        in_channel = channel_number[-1]
        
        # Nhánh phân loại real/fake (adversarial)
        self.classifier_adv = nn.Sequential(
            nn.Conv2d(in_channel, 1, kernel_size=3, padding=0, bias=False),
            nn.AdaptiveAvgPool2d(1),  # Global average pooling để giảm kích thước xuống 1x1
            nn.Flatten(),
            nn.Sigmoid()  # Sigmoid cho phân loại nhị phân (real/fake)
        )
        
        # Nhánh phân loại giới tính
        self.classifier_gender = nn.Sequential(
            nn.Conv2d(in_channel, 8, kernel_size=3, padding=0, bias=False),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d(1),  # Global average pooling
            nn.Flatten(),
            nn.Linear(8, 1),
            nn.Sigmoid()  # Sigmoid cho phân loại nhị phân (nam/nữ)
        )
        
        # Nhánh hồi quy tuổi
        self.classifier_age = nn.Sequential(
            nn.Conv2d(in_channel, 16, kernel_size=3, padding=0, bias=False),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d(1),  # Global average pooling
            nn.Flatten(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 1)  # Không có activation để dự đoán giá trị thực
        )

    def forward(self, x):
        '''
        :param x: Tensor hình ảnh đầu vào có dạng (batch_size, 3, H, W)
        :return: Tuple gồm (adv_preds, gender_preds, age_preds) tương ứng với 3 đầu ra
        '''
        # Trích xuất đặc trưng chung cho cả 3 tác vụ
        encoded_features = self.feature_extractor(x)
        
        # Áp dụng 3 nhánh dự đoán
        adv_preds = self.classifier_adv(encoded_features)
        gender_preds = self.classifier_gender(encoded_features)
        age_preds = self.classifier_age(encoded_features)
        
        return adv_preds, gender_preds, age_preds

In [14]:
# Hàm kiểm tra kích thước đầu ra
def test_discriminator():
    batch_size = 4
    height, width = 128, 128  # Giả sử kích thước ảnh đầu vào là 128x128
    
    # Tạo tensor đầu vào ngẫu nhiên
    x = torch.randn(batch_size, 3, height, width)
    
    # Khởi tạo discriminator
    discriminator = Discriminator()
    
    total_params = sum(p.numel() for p in discriminator.parameters())
    print(f"Discriminator total parameters: {total_params:,}")
          
    # Áp dụng discriminator
    adv_preds, gender_preds, age_preds = discriminator(x)
    
    # In kích thước đầu ra
    print(f"Discriminator input shape: {x.shape}")
    print(f"Adversarial predictions shape: {adv_preds.shape}")  # Kỳ vọng: [batch_size, 1]
    print(f"Gender predictions shape: {gender_preds.shape}")    # Kỳ vọng: [batch_size, 1]
    print(f"Age predictions shape: {age_preds.shape}")          # Kỳ vọng: [batch_size, 1]
    
    return discriminator

if __name__ == "__main__":
    test_discriminator()

Discriminator total parameters: 424,730
Discriminator input shape: torch.Size([4, 3, 128, 128])
Adversarial predictions shape: torch.Size([4, 1])
Gender predictions shape: torch.Size([4, 1])
Age predictions shape: torch.Size([4, 1])

# Training

In [ ]:
from tqdm import tqdm

# Định nghĩa các hàm loss
def adversarial_loss(preds, target):
    """Loss cho phân loại real/fake"""
    return nn.BCELoss()(preds, target)

def gender_loss(preds, target):
    """Loss cho phân loại giới tính"""
    return nn.BCELoss()(preds, target)

def age_loss(preds, target):
    """Loss cho hồi quy tuổi"""
    return nn.L1Loss()(preds, target)

def train_gan(generator, discriminator, dataloader, num_epochs=100, 
              lr_g=2e-4, lr_d=2e-4, beta1=0.5, beta2=0.999,
              lambda_adv=1.0, lambda_gender=1.0, lambda_age=1.0,
              checkpoint_dir='checkpoints', save_freq=5, device=None,
              result_dir='results', img_dir='images'):
    """
    Training loop cho GAN MRI phản thực
    
    Args:
        generator: Mô hình Generator
        discriminator: Mô hình Discriminator
        dataloader: DataLoader cho dữ liệu training
        num_epochs: Số epoch training
        lr_g: Learning rate cho Generator
        lr_d: Learning rate cho Discriminator
        beta1, beta2: Các tham số cho Adam optimizer
        lambda_adv, lambda_gender, lambda_age: Trọng số cho các loss
        checkpoint_dir: Thư mục lưu checkpoint
        save_freq: Tần suất lưu checkpoint (số epoch)
        device: Thiết bị tính toán (CPU/GPU)
        result_dir: Thư mục lưu đồ thị loss
        img_dir: Thư mục lưu kết quả ảnh sinh
    """
    # Thiết lập thiết bị tính toán
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    
    # Chuyển các mô hình sang thiết bị
    generator.to(device)
    discriminator.to(device)
    
    # Khởi tạo các optimizer
    optimizer_G = optim.Adam(generator.parameters(), lr=lr_g, betas=(beta1, beta2))
    optimizer_D = optim.Adam(discriminator.parameters(), lr=lr_d, betas=(beta1, beta2))
    
    # Tạo thư mục lưu checkpoint và kết quả nếu chưa tồn tại
    os.makedirs(checkpoint_dir, exist_ok=True)
    os.makedirs(result_dir, exist_ok=True)
    os.makedirs(img_dir, exist_ok=True)
    
    # Khởi tạo tensors cho label real/fake
    real_label = 1.0
    fake_label = 0.0
    
    # Lists để lưu lịch sử loss
    loss_history = {
        'D_total': [], 'D_real': [], 'D_fake': [], 'D_gender': [], 'D_age': [],
        'G_total': [], 'G_adv': [], 'G_gender': [], 'G_age': []
    }
    
    # Training loop
    total_start_time = time.time()
    
    for epoch in range(1, num_epochs + 1):
        
        # Khởi tạo các biến tích lũy loss
        running_loss_D_total = 0.0
        running_loss_D_real = 0.0
        running_loss_D_fake = 0.0
        running_loss_D_gender = 0.0
        running_loss_D_age = 0.0
        running_loss_G_total = 0.0
        running_loss_G_adv = 0.0
        running_loss_G_gender = 0.0
        running_loss_G_age = 0.0
        
        # Lặp qua các batch dữ liệu
        with tqdm(dataloader, desc=f"Epoch {epoch}/{num_epochs}") as pbar:
            for i, batch in enumerate(pbar):
                # Di chuyển dữ liệu sang thiết bị
                real_imgs = batch['real_img'].to(device)
                real_conditions = batch['real_condition'].to(device)
                cf_conditions = batch['cf_condition'].to(device)
                
                # Lấy thông tin điều kiện gốc (không chuẩn hóa) để ghi log
                real_raw_conditions = batch['real_raw_condition'].to(device)
                cf_raw_conditions = batch['cf_raw_condition'].to(device)
                
                # Get sample IDs for visualization
                real_ids = batch['real_id']
                cf_ids = batch['cf_id']
                
                batch_size = real_imgs.size(0)
                
                # Chuẩn bị labels
                real_targets = torch.full((batch_size, 1), real_label, device=device)
                fake_targets = torch.full((batch_size, 1), fake_label, device=device)
                
                # Trích xuất thông tin giới tính và tuổi
                real_gender = real_conditions[:, 1].view(-1, 1)
                real_age = real_raw_conditions[:, 0].view(-1, 1)
                cf_gender = cf_conditions[:, 1].view(-1, 1)
                cf_age = cf_raw_conditions[:, 0].view(-1, 1)
                
                # -------------------------------
                # Huấn luyện Discriminator
                # -------------------------------
                optimizer_D.zero_grad()
                
                # Tính loss cho ảnh thật
                real_adv_preds, real_gender_preds, real_age_preds = discriminator(real_imgs)
                
                loss_D_real_adv = adversarial_loss(real_adv_preds, real_targets)
                loss_D_real_gender = gender_loss(real_gender_preds, real_gender)
                loss_D_real_age = age_loss(real_age_preds, real_age)
                
                loss_D_real = loss_D_real_adv + lambda_gender * loss_D_real_gender + lambda_age * loss_D_real_age
                
                # Tạo ảnh giả
                fake_imgs, _ = generator(real_imgs, cf_conditions)
                
                # Tính loss cho ảnh giả
                fake_adv_preds, fake_gender_preds, fake_age_preds = discriminator(fake_imgs.detach())
                
                loss_D_fake_adv = adversarial_loss(fake_adv_preds, fake_targets)
                loss_D_fake_gender = gender_loss(fake_gender_preds, cf_gender)
                loss_D_fake_age = age_loss(fake_age_preds, cf_age)
                
                loss_D_fake = loss_D_fake_adv + lambda_gender * loss_D_fake_gender + lambda_age * loss_D_fake_age
                
                # Tổng hợp loss cho Discriminator
                loss_D = (loss_D_real + loss_D_fake) / 2
                
                # Backward và optimize
                loss_D.backward()
                optimizer_D.step()
                
                # -------------------------------
                # Huấn luyện Generator
                # -------------------------------
                optimizer_G.zero_grad()
                
                # Sinh ảnh giả một lần nữa để tính toán loss G
                fake_imgs, _ = generator(real_imgs, cf_conditions)
                
                # Phân loại ảnh giả bằng Discriminator
                fake_adv_preds, fake_gender_preds, fake_age_preds = discriminator(fake_imgs)
                
                # Tính các loss cho Generator
                loss_G_adv = adversarial_loss(fake_adv_preds, real_targets)  # Đánh lừa D nghĩ rằng ảnh giả là thật
                loss_G_gender = gender_loss(fake_gender_preds, cf_gender)    # Khớp với giới tính mục tiêu
                loss_G_age = age_loss(fake_age_preds, cf_age)                # Khớp với tuổi mục tiêu
                
                # Tổng hợp loss cho Generator
                loss_G = lambda_adv * loss_G_adv + lambda_gender * loss_G_gender + lambda_age * loss_G_age
                
                # Backward và optimize
                loss_G.backward()
                optimizer_G.step()
                
                # -------------------------------
                # Cập nhật các loss tích lũy
                # -------------------------------
                running_loss_D_total += loss_D.item()
                running_loss_D_real += loss_D_real_adv.item()
                running_loss_D_fake += loss_D_fake_adv.item()
                running_loss_D_gender += (loss_D_real_gender.item() + loss_D_fake_gender.item()) / 2
                running_loss_D_age += (loss_D_real_age.item() + loss_D_fake_age.item()) / 2
                
                running_loss_G_total += loss_G.item()
                running_loss_G_adv += loss_G_adv.item()
                running_loss_G_gender += loss_G_gender.item()
                running_loss_G_age += loss_G_age.item()
                
                # Cập nhật thanh tiến độ
                pbar.set_postfix({
                    'D_loss': f"{loss_D.item():.4f}",
                    'G_loss': f"{loss_G.item():.4f}"
                })
                
                # Trực quan hóa kết quả cho batch cuối mỗi epoch
                if i == len(dataloader) - 1:
                    visualize_results(real_imgs, fake_imgs, 
                                     real_raw_conditions, cf_raw_conditions,
                                     real_ids, cf_ids,
                                     epoch, img_dir)
        
        # Tính loss trung bình cho epoch
        avg_loss_D_total = running_loss_D_total / len(dataloader)
        avg_loss_D_real = running_loss_D_real / len(dataloader)
        avg_loss_D_fake = running_loss_D_fake / len(dataloader)
        avg_loss_D_gender = running_loss_D_gender / len(dataloader)
        avg_loss_D_age = running_loss_D_age / len(dataloader)
        
        avg_loss_G_total = running_loss_G_total / len(dataloader)
        avg_loss_G_adv = running_loss_G_adv / len(dataloader)
        avg_loss_G_gender = running_loss_G_gender / len(dataloader)
        avg_loss_G_age = running_loss_G_age / len(dataloader)
        
        # Lưu lịch sử loss
        loss_history['D_total'].append(avg_loss_D_total)
        loss_history['D_real'].append(avg_loss_D_real)
        loss_history['D_fake'].append(avg_loss_D_fake)
        loss_history['D_gender'].append(avg_loss_D_gender)
        loss_history['D_age'].append(avg_loss_D_age)
        
        loss_history['G_total'].append(avg_loss_G_total)
        loss_history['G_adv'].append(avg_loss_G_adv)
        loss_history['G_gender'].append(avg_loss_G_gender)
        loss_history['G_age'].append(avg_loss_G_age)
        
        # In thông tin loss cho epoch
        print(f"D_total: {avg_loss_D_total:.4f}, D_real: {avg_loss_D_real:.4f}, D_fake: {avg_loss_D_fake:.4f}, "
              f"D_gender: {avg_loss_D_gender:.4f}, D_age: {avg_loss_D_age:.4f}")
        print(f"G_total: {avg_loss_G_total:.4f}, G_adv: {avg_loss_G_adv:.4f}, "
              f"G_gender: {avg_loss_G_gender:.4f}, G_age: {avg_loss_G_age:.4f}")
        
        # Lưu checkpoint sau mỗi 'save_freq' epoch
        if epoch % save_freq == 0 or epoch == num_epochs:
            save_checkpoint(generator, discriminator, optimizer_G, optimizer_D, 
                           loss_history, epoch, checkpoint_dir)
            
            # Vẽ đồ thị loss
            plot_losses(loss_history, epoch, result_dir)
    
    total_time = time.time() - total_start_time
    print(f"Training completed after {total_time:.2f} seconds.")
    
    # Vẽ đồ thị loss cuối cùng
    plot_losses(loss_history, num_epochs, result_dir)
    
    return loss_history

def save_checkpoint(generator, discriminator, optimizer_G, optimizer_D, 
                   loss_history, epoch, checkpoint_dir):
    """Lưu trạng thái của mô hình và optimizer"""
    checkpoint_path = os.path.join(checkpoint_dir, f"checkpoint_epoch_{epoch}.pth")
    
    checkpoint = {
        'epoch': epoch,
        'generator': generator.state_dict(),
        'discriminator': discriminator.state_dict(),
        'optimizer_G': optimizer_G.state_dict(),
        'optimizer_D': optimizer_D.state_dict(),
        'loss_history': loss_history
    }
    
    torch.save(checkpoint, checkpoint_path)
    print(f"Saved checkpoint at epoch {epoch} in: {checkpoint_path}\n")

def visualize_results(real_imgs, fake_imgs, real_conditions, cf_conditions, real_ids=None, cf_ids=None, epoch=None, img_dir=None):
    """
    Visualize real and generated images, separated into 3 distinct slices (axial, sagittal, coronal)
    
    Args:
        real_imgs: Tensor of real images [batch_size, 3, H, W]
        fake_imgs: Tensor of generated images [batch_size, 3, H, W]
        real_conditions: Original condition information
        cf_conditions: Target condition information
        real_ids: IDs of real samples (optional)
        cf_ids: IDs of counterfactual condition samples (optional)
        epoch: Current epoch
        img_dir: Directory to save result images
    """
    # Skip visualization if not a multiple of 5 epochs (except for the first and last epochs)
    if epoch is not None and epoch > 1 and epoch % 5 != 0:
        return
        
    # Move to CPU
    real_imgs = real_imgs.detach().cpu()
    fake_imgs = fake_imgs.detach().cpu()
    
    # Limit number of displayed images
    num_samples = min(4, real_imgs.size(0))
    
    # Create figure with larger subplot size
    fig = plt.figure(figsize=(15, 5 * num_samples))
    
    # Create a GridSpec layout
    gs = plt.GridSpec(2 * num_samples, 4, figure=fig, width_ratios=[1, 1, 1, 0.2])
    
    for i in range(num_samples):
        # Get age and gender information
        real_age = real_conditions[i, 0].item()
        real_gender = "Female" if real_conditions[i, 1].item() > 0.5 else "Male"
        cf_age = cf_conditions[i, 0].item()
        cf_gender = "Female" if cf_conditions[i, 1].item() > 0.5 else "Male"
        
        row_real = i * 2
        row_fake = i * 2 + 1
        
        # Add row titles
        title_ax_real = fig.add_subplot(gs[row_real, :])
        title_ax_real.set_title(f"Sample {i+1} - Real: {real_age} years old, {real_gender}", fontsize=14)
        title_ax_real.axis('off')
        
        title_ax_fake = fig.add_subplot(gs[row_fake, :])
        title_ax_fake.set_title(f"Sample {i+1} - Fake: {cf_age} years old, {cf_gender}", fontsize=14)
        title_ax_fake.axis('off')
        
        # Process each slice
        for j in range(3):
            # Extract individual slices from 3-channel images
            real_slice = real_imgs[i, j].numpy()
            fake_slice = fake_imgs[i, j].numpy()
            
            # Normalize pixel values to [0, 1]
            real_slice = (real_slice - real_slice.min()) / (real_slice.max() - real_slice.min() + 1e-8)
            fake_slice = (fake_slice - fake_slice.min()) / (fake_slice.max() - fake_slice.min() + 1e-8)
            
            # Display images - adjust the position to leave space for titles
            ax_real = fig.add_subplot(gs[row_real, j])
            ax_real.imshow(real_slice, cmap='gray')
            ax_real.axis('off')
            
            ax_fake = fig.add_subplot(gs[row_fake, j])
            ax_fake.imshow(fake_slice, cmap='gray')
            ax_fake.axis('off')
    
    plt.tight_layout(h_pad=2, w_pad=1)
    if img_dir and epoch is not None:
        plt.savefig(os.path.join(img_dir, f"image_epoch_{epoch}.png"), dpi=300, bbox_inches='tight')
    plt.close()
    
    # Create detailed visualization for the first sample
    if num_samples > 0:
        create_detailed_visualization(
            real_imgs[0], fake_imgs[0],
            real_age=real_conditions[0, 0].item(),
            real_gender="Female" if real_conditions[0, 1].item() > 0.5 else "Male",
            cf_age=cf_conditions[0, 0].item(),
            cf_gender="Female" if cf_conditions[0, 1].item() > 0.5 else "Male",
            real_id=real_ids[0] if real_ids is not None else None,
            cf_id=cf_ids[0] if cf_ids is not None else None,
            epoch=epoch,
            img_dir=img_dir
        )

def create_detailed_visualization(real_img, fake_img, real_age, real_gender, cf_age, cf_gender, 
                                 real_id=None, cf_id=None, epoch=None, img_dir=None):
    """
    Create a more detailed visualization for a sample for deeper analysis
    """
    slice_names = ["Axial", "Sagittal", "Coronal"]
    
    fig, axes = plt.subplots(2, 4, figsize=(18, 9))
    
    # Display each real slice
    for j in range(3):
        real_slice = real_img[j].numpy()
        real_slice = (real_slice - real_slice.min()) / (real_slice.max() - real_slice.min() + 1e-8)
        axes[0, j].imshow(real_slice, cmap='gray')
        axes[0, j].set_title(f"Real - {slice_names[j]}", fontsize=12)
        axes[0, j].axis('off')
    
    # Display each fake slice
    for j in range(3):
        fake_slice = fake_img[j].numpy()
        fake_slice = (fake_slice - fake_slice.min()) / (fake_slice.max() - fake_slice.min() + 1e-8)
        axes[1, j].imshow(fake_slice, cmap='gray')
        axes[1, j].set_title(f"Fake - {slice_names[j]}", fontsize=12)
        axes[1, j].axis('off')
    
    # Display difference between real and fake (for first slice)
    real_slice_0 = real_img[0].numpy()
    real_slice_0 = (real_slice_0 - real_slice_0.min()) / (real_slice_0.max() - real_slice_0.min() + 1e-8)
    fake_slice_0 = fake_img[0].numpy()
    fake_slice_0 = (fake_slice_0 - fake_slice_0.min()) / (fake_slice_0.max() - fake_slice_0.min() + 1e-8)
    
    diff = np.abs(real_slice_0 - fake_slice_0)
    
    axes[0, 3].imshow(diff, cmap='hot')
    axes[0, 3].set_title("Difference (Axial)", fontsize=12)
    axes[0, 3].axis('off')
    
    # Display sample information
    axes[1, 3].axis('off')
    
    # Build information text including IDs if available
    info_text = [
        "Sample Information:\n",
        f"Real: {real_age} years old, {real_gender}",
        f"Fake: {cf_age} years old, {cf_gender}\n",
        "Change:",
        f"Age: {real_age} → {cf_age}",
        f"Gender: {real_gender} → {cf_gender}"
    ]
    
    # Add IDs if available
    if real_id is not None:
        info_text.append(f"\nReal Sample ID: {real_id}")
    if cf_id is not None:
        info_text.append(f"Condition Source ID: {cf_id}")
        
    axes[1, 3].text(0.1, 0.5, "\n".join(info_text), fontsize=12, va='center')
    
    plt.tight_layout()
    if img_dir and epoch is not None:
        plt.savefig(os.path.join(img_dir, f"detailed_result_epoch_{epoch}.png"), dpi=300, bbox_inches='tight')
    plt.close()

def plot_losses(loss_history, epoch, result_dir):
    """Vẽ đồ thị các loss theo thời gian"""
    # Tạo subplot cho loss của Discriminator
    plt.figure(figsize=(12, 10))
    
    plt.subplot(2, 1, 1)
    plt.plot(loss_history['D_total'], label='D Total')
    plt.plot(loss_history['D_real'], label='D Real')
    plt.plot(loss_history['D_fake'], label='D Fake')
    plt.plot(loss_history['D_gender'], label='D Gender')
    plt.plot(loss_history['D_age'], label='D Age')
    plt.title('Discriminator Losses')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    
    # Subplot cho loss của Generator
    plt.subplot(2, 1, 2)
    plt.plot(loss_history['G_total'], label='G Total')
    plt.plot(loss_history['G_adv'], label='G Adversarial')
    plt.plot(loss_history['G_gender'], label='G Gender')
    plt.plot(loss_history['G_age'], label='G Age')
    plt.title('Generator Losses')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    
    plt.tight_layout()
    plt.savefig(os.path.join(result_dir, f"losses_epoch_{epoch}.png"))
    plt.close()

In [ ]:
def main():
    """Hàm chính để khởi chạy quá trình training"""
    # Thiết lập các thông số
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    batch_size = 12
    num_workers = 4
    lr_g = 5e-4
    lr_d = 2e-4
    beta1 = 0.5
    beta2 = 0.999
    num_epochs = 300
    save_freq = 5
    checkpoint_dir = 'GAN/src/CounterSynth/checkpoints'
    result_dir = 'GAN/src/CounterSynth/results'
    img_dir = 'GAN/src/CounterSynth/images1'
    
    # Thiết lập các trọng số loss
    lambda_adv = 1.0
    lambda_gender = 0.8
    lambda_age = 0.5
    
    # Tạo dataset và dataloader
    transform = None  # Nếu cần transform thêm
    dataset = BrainMRIDataset(
        data_dir='data',
        participants_file='data/participants_1.xlsx',
        transform=transform
    )
    
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True
    )
    
    # Khởi tạo các mô hình
    generator = MultiSliceGenerator()
    discriminator = Discriminator(in_channels=3)
    
    # Khởi tạo trọng số
    generator.apply(weights_init_normal)
    discriminator.apply(weights_init_normal)
    
    # Chuyển các mô hình sang thiết bị
    generator.to(device)
    discriminator.to(device)
    
    # Khởi chạy quá trình training
    loss_history = train_gan(
        generator=generator,
        discriminator=discriminator,
        dataloader=dataloader,
        num_epochs=num_epochs,
        lr_g=lr_g,
        lr_d=lr_d,
        beta1=beta1,
        beta2=beta2,
        lambda_adv=lambda_adv,
        lambda_gender=lambda_gender,
        lambda_age=lambda_age,
        checkpoint_dir=checkpoint_dir,
        save_freq=save_freq,
        device=device,
        result_dir=result_dir,
        img_dir=img_dir
    )
    
    return loss_history

if __name__ == "__main__":
    main()

Found 4924 samples with valid MRI data
Using device: cuda

Epoch 1/300: 100%|██████████| 411/411 [01:08<00:00,  5.98it/s, D_loss=8.1921, G_loss=10.4141]

D_total: 17.0916, D_real: 0.6615, D_fake: 0.6699, D_gender: 0.6778, D_age: 31.7674
G_total: 16.7458, G_adv: 0.7397, G_gender: 0.6773, G_age: 30.9284

Epoch 2/300: 100%|██████████| 411/411 [01:05<00:00,  6.31it/s, D_loss=7.2194, G_loss=9.3126]

D_total: 5.7956, D_real: 0.3690, D_fake: 0.3628, D_gender: 0.6792, D_age: 9.7727
G_total: 5.5360, G_adv: 1.5865, G_gender: 0.6799, G_age: 6.8112

Epoch 3/300: 100%|██████████| 411/411 [01:04<00:00,  6.42it/s, D_loss=11.2416, G_loss=16.2593]

D_total: 5.6930, D_real: 0.4206, D_fake: 0.4211, D_gender: 0.6772, D_age: 9.4608
G_total: 5.4884, G_adv: 1.4718, G_gender: 0.6813, G_age: 6.9431

Epoch 4/300: 100%|██████████| 411/411 [01:04<00:00,  6.41it/s, D_loss=7.1739, G_loss=5.6941]

D_total: 5.7037, D_real: 0.3910, D_fake: 0.3909, D_gender: 0.6693, D_age: 9.5546
G_total: 5.7099, G_adv: 1.6574, G_gender: 0.6849, G_age: 7.0092

Epoch 5/300: 100%|██████████| 411/411 [01:08<00:00,  5.98it/s, D_loss=2.6578, G_loss=4.7070]

D_total: 5.7163, D_real: 0.3827, D_fake: 0.3822, D_gender: 0.6550, D_age: 9.6197
G_total: 5.9541, G_adv: 1.7942, G_gender: 0.6899, G_age: 7.2160
Saved checkpoint at epoch 5 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_5.pth

Epoch 6/300: 100%|██████████| 411/411 [01:03<00:00,  6.50it/s, D_loss=6.7353, G_loss=5.1988]

D_total: 5.7491, D_real: 0.4035, D_fake: 0.4133, D_gender: 0.6350, D_age: 9.6654
G_total: 5.8351, G_adv: 1.7224, G_gender: 0.6898, G_age: 7.1215

Epoch 7/300: 100%|██████████| 411/411 [01:02<00:00,  6.56it/s, D_loss=7.3347, G_loss=4.4196]

D_total: 5.5876, D_real: 0.3921, D_fake: 0.3905, D_gender: 0.6265, D_age: 9.3904
G_total: 5.7939, G_adv: 1.7504, G_gender: 0.7053, G_age: 6.9585

Epoch 8/300: 100%|██████████| 411/411 [01:04<00:00,  6.41it/s, D_loss=5.0336, G_loss=5.4163]

D_total: 5.6014, D_real: 0.3880, D_fake: 0.3938, D_gender: 0.6183, D_age: 9.4318
G_total: 5.8230, G_adv: 1.7216, G_gender: 0.7044, G_age: 7.0759

Epoch 9/300: 100%|██████████| 411/411 [01:03<00:00,  6.48it/s, D_loss=4.1576, G_loss=3.4855]

D_total: 5.4703, D_real: 0.3789, D_fake: 0.3934, D_gender: 0.6156, D_age: 9.1833
G_total: 5.7716, G_adv: 1.6975, G_gender: 0.7190, G_age: 6.9978

Epoch 10/300: 100%|██████████| 411/411 [01:09<00:00,  5.90it/s, D_loss=5.3280, G_loss=5.3769]

D_total: 5.5895, D_real: 0.3807, D_fake: 0.3923, D_gender: 0.6022, D_age: 9.4424
G_total: 5.8972, G_adv: 1.6928, G_gender: 0.7028, G_age: 7.2843
Saved checkpoint at epoch 10 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_10.pth

Epoch 11/300: 100%|██████████| 411/411 [01:02<00:00,  6.61it/s, D_loss=9.1907, G_loss=8.7580]

D_total: 5.4264, D_real: 0.3575, D_fake: 0.3623, D_gender: 0.6012, D_age: 9.1710
G_total: 5.9029, G_adv: 1.8749, G_gender: 0.7128, G_age: 6.9154

Epoch 12/300: 100%|██████████| 411/411 [01:01<00:00,  6.66it/s, D_loss=6.4157, G_loss=7.8860]

D_total: 5.3802, D_real: 0.3796, D_fake: 0.3831, D_gender: 0.5954, D_age: 9.0452
G_total: 5.7461, G_adv: 1.7482, G_gender: 0.7206, G_age: 6.8427

Epoch 13/300: 100%|██████████| 411/411 [01:03<00:00,  6.45it/s, D_loss=5.3602, G_loss=6.8379]

D_total: 5.3268, D_real: 0.3745, D_fake: 0.3819, D_gender: 0.6013, D_age: 8.9353
G_total: 5.6688, G_adv: 1.6796, G_gender: 0.7370, G_age: 6.7992

Epoch 14/300: 100%|██████████| 411/411 [01:03<00:00,  6.50it/s, D_loss=6.4534, G_loss=9.3556]

D_total: 5.3409, D_real: 0.3715, D_fake: 0.3811, D_gender: 0.5934, D_age: 8.9797
G_total: 5.8055, G_adv: 1.7506, G_gender: 0.7254, G_age: 6.9494

Epoch 15/300: 100%|██████████| 411/411 [01:10<00:00,  5.84it/s, D_loss=12.0011, G_loss=10.0267]

D_total: 5.3796, D_real: 0.3821, D_fake: 0.3887, D_gender: 0.5787, D_age: 9.0626
G_total: 5.8345, G_adv: 1.7503, G_gender: 0.6963, G_age: 7.0543
Saved checkpoint at epoch 15 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_15.pth

Epoch 16/300: 100%|██████████| 411/411 [01:04<00:00,  6.33it/s, D_loss=6.6153, G_loss=4.0681]

D_total: 5.1867, D_real: 0.3482, D_fake: 0.3647, D_gender: 0.5528, D_age: 8.7761
G_total: 5.6256, G_adv: 1.8017, G_gender: 0.6506, G_age: 6.6069

Epoch 17/300: 100%|██████████| 411/411 [01:05<00:00,  6.32it/s, D_loss=8.7395, G_loss=10.4268]

D_total: 5.1546, D_real: 0.3442, D_fake: 0.3540, D_gender: 0.5393, D_age: 8.7480
G_total: 5.6661, G_adv: 1.7811, G_gender: 0.6173, G_age: 6.7822

Epoch 18/300: 100%|██████████| 411/411 [00:59<00:00,  6.96it/s, D_loss=4.3917, G_loss=5.8607]

D_total: 5.0887, D_real: 0.3532, D_fake: 0.3667, D_gender: 0.5402, D_age: 8.5930
G_total: 5.6773, G_adv: 1.7802, G_gender: 0.6253, G_age: 6.7937

Epoch 19/300: 100%|██████████| 411/411 [01:01<00:00,  6.68it/s, D_loss=5.5392, G_loss=5.8615]

D_total: 4.9782, D_real: 0.3200, D_fake: 0.3274, D_gender: 0.5071, D_age: 8.4976
G_total: 5.6966, G_adv: 1.9520, G_gender: 0.5702, G_age: 6.5770

Epoch 20/300: 100%|██████████| 411/411 [01:08<00:00,  5.97it/s, D_loss=6.0103, G_loss=7.3261]

D_total: 5.0138, D_real: 0.3294, D_fake: 0.3434, D_gender: 0.4922, D_age: 8.5673
G_total: 5.7033, G_adv: 1.9546, G_gender: 0.5291, G_age: 6.6506
Saved checkpoint at epoch 20 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_20.pth

Epoch 21/300: 100%|██████████| 411/411 [01:03<00:00,  6.49it/s, D_loss=9.7472, G_loss=10.6341]

D_total: 4.9865, D_real: 0.3199, D_fake: 0.3287, D_gender: 0.4594, D_age: 8.5892
G_total: 5.7902, G_adv: 1.9724, G_gender: 0.4656, G_age: 6.8905

Epoch 22/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=2.7530, G_loss=3.3033]

D_total: 4.8733, D_real: 0.3022, D_fake: 0.3151, D_gender: 0.4284, D_age: 8.4440
G_total: 5.7538, G_adv: 2.0213, G_gender: 0.4202, G_age: 6.7928

Epoch 23/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=6.3386, G_loss=10.4123]

D_total: 4.8851, D_real: 0.3179, D_fake: 0.3334, D_gender: 0.4385, D_age: 8.4174
G_total: 5.6689, G_adv: 1.9725, G_gender: 0.4266, G_age: 6.7102

Epoch 24/300: 100%|██████████| 411/411 [01:03<00:00,  6.48it/s, D_loss=3.8190, G_loss=4.6923]

D_total: 4.8961, D_real: 0.3247, D_fake: 0.3341, D_gender: 0.4417, D_age: 8.4267
G_total: 5.7385, G_adv: 1.9760, G_gender: 0.4298, G_age: 6.8373

Epoch 25/300: 100%|██████████| 411/411 [01:08<00:00,  6.02it/s, D_loss=6.4658, G_loss=5.6287]

D_total: 4.8443, D_real: 0.3237, D_fake: 0.3289, D_gender: 0.4383, D_age: 8.3348
G_total: 5.7038, G_adv: 2.0195, G_gender: 0.4184, G_age: 6.6992
Saved checkpoint at epoch 25 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_25.pth

Epoch 26/300: 100%|██████████| 411/411 [01:03<00:00,  6.51it/s, D_loss=3.5924, G_loss=6.9344]

D_total: 4.7387, D_real: 0.3367, D_fake: 0.3501, D_gender: 0.4235, D_age: 8.1129
G_total: 5.6195, G_adv: 1.9892, G_gender: 0.3975, G_age: 6.6246

Epoch 27/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=6.5982, G_loss=9.9428]

D_total: 4.7237, D_real: 0.3081, D_fake: 0.3263, D_gender: 0.4131, D_age: 8.1520
G_total: 5.6354, G_adv: 2.0397, G_gender: 0.3853, G_age: 6.5750

Epoch 28/300: 100%|██████████| 411/411 [01:06<00:00,  6.21it/s, D_loss=3.6227, G_loss=4.9924]

D_total: 4.7245, D_real: 0.3198, D_fake: 0.3334, D_gender: 0.4031, D_age: 8.1508
G_total: 5.6702, G_adv: 2.0093, G_gender: 0.3738, G_age: 6.7237

Epoch 29/300: 100%|██████████| 411/411 [01:04<00:00,  6.34it/s, D_loss=6.2504, G_loss=7.4868]

D_total: 4.7676, D_real: 0.3241, D_fake: 0.3317, D_gender: 0.4062, D_age: 8.2295
G_total: 5.6075, G_adv: 1.9752, G_gender: 0.3760, G_age: 6.6629

Epoch 30/300: 100%|██████████| 411/411 [01:09<00:00,  5.94it/s, D_loss=6.0327, G_loss=11.1461]

D_total: 4.7697, D_real: 0.3170, D_fake: 0.3375, D_gender: 0.4095, D_age: 8.2296
G_total: 5.5418, G_adv: 1.9502, G_gender: 0.3796, G_age: 6.5758
Saved checkpoint at epoch 30 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_30.pth

Epoch 31/300: 100%|██████████| 411/411 [01:02<00:00,  6.58it/s, D_loss=5.7085, G_loss=6.2460]

D_total: 4.7838, D_real: 0.3259, D_fake: 0.3409, D_gender: 0.4136, D_age: 8.2390
G_total: 5.6527, G_adv: 1.9708, G_gender: 0.3966, G_age: 6.7294

Epoch 32/300: 100%|██████████| 411/411 [01:03<00:00,  6.49it/s, D_loss=3.7387, G_loss=6.1470]

D_total: 4.6421, D_real: 0.3151, D_fake: 0.3248, D_gender: 0.4082, D_age: 7.9910
G_total: 5.6413, G_adv: 2.0343, G_gender: 0.3835, G_age: 6.6003

Epoch 33/300: 100%|██████████| 411/411 [01:03<00:00,  6.45it/s, D_loss=3.3235, G_loss=5.1835]

D_total: 4.7013, D_real: 0.3091, D_fake: 0.3256, D_gender: 0.4039, D_age: 8.1215
G_total: 5.7846, G_adv: 2.1115, G_gender: 0.3719, G_age: 6.7512

Epoch 34/300: 100%|██████████| 411/411 [01:02<00:00,  6.57it/s, D_loss=3.9930, G_loss=7.4278]

D_total: 4.7718, D_real: 0.3314, D_fake: 0.3407, D_gender: 0.4132, D_age: 8.2103
G_total: 5.7416, G_adv: 2.0462, G_gender: 0.3887, G_age: 6.7689

Epoch 35/300: 100%|██████████| 411/411 [01:07<00:00,  6.09it/s, D_loss=4.0914, G_loss=4.5873]

D_total: 4.6438, D_real: 0.3153, D_fake: 0.3314, D_gender: 0.3967, D_age: 8.0061
G_total: 5.7338, G_adv: 2.1261, G_gender: 0.3839, G_age: 6.6012
Saved checkpoint at epoch 35 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_35.pth

Epoch 36/300: 100%|██████████| 411/411 [01:02<00:00,  6.61it/s, D_loss=6.2386, G_loss=6.9575]

D_total: 4.6928, D_real: 0.3205, D_fake: 0.3248, D_gender: 0.4000, D_age: 8.1004
G_total: 5.8648, G_adv: 2.0800, G_gender: 0.3674, G_age: 6.9817

Epoch 37/300: 100%|██████████| 411/411 [01:02<00:00,  6.57it/s, D_loss=5.0718, G_loss=7.4595]

D_total: 4.5580, D_real: 0.3097, D_fake: 0.3321, D_gender: 0.3606, D_age: 7.8973
G_total: 5.6727, G_adv: 2.1014, G_gender: 0.3161, G_age: 6.6368

Epoch 38/300: 100%|██████████| 411/411 [01:03<00:00,  6.51it/s, D_loss=6.0675, G_loss=8.5450]

D_total: 4.5140, D_real: 0.3151, D_fake: 0.3409, D_gender: 0.3472, D_age: 7.8165
G_total: 5.5676, G_adv: 2.0859, G_gender: 0.2889, G_age: 6.5012

Epoch 39/300: 100%|██████████| 411/411 [01:03<00:00,  6.46it/s, D_loss=4.2529, G_loss=7.0342]

D_total: 4.5411, D_real: 0.3062, D_fake: 0.3191, D_gender: 0.3442, D_age: 7.9061
G_total: 5.6215, G_adv: 2.1548, G_gender: 0.2759, G_age: 6.4919

Epoch 40/300: 100%|██████████| 411/411 [01:07<00:00,  6.05it/s, D_loss=6.1219, G_loss=7.6434]

D_total: 4.6102, D_real: 0.2827, D_fake: 0.2975, D_gender: 0.3432, D_age: 8.0910
G_total: 6.0191, G_adv: 2.2910, G_gender: 0.2871, G_age: 6.9969
Saved checkpoint at epoch 40 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_40.pth

Epoch 41/300: 100%|██████████| 411/411 [01:02<00:00,  6.55it/s, D_loss=5.7030, G_loss=5.4080]

D_total: 4.6096, D_real: 0.3122, D_fake: 0.3352, D_gender: 0.3336, D_age: 8.0380
G_total: 5.8328, G_adv: 2.1904, G_gender: 0.2728, G_age: 6.8484

Epoch 42/300: 100%|██████████| 411/411 [01:02<00:00,  6.57it/s, D_loss=5.5117, G_loss=5.4478]

D_total: 4.4651, D_real: 0.3125, D_fake: 0.3358, D_gender: 0.3401, D_age: 7.7378
G_total: 5.6015, G_adv: 2.1476, G_gender: 0.2744, G_age: 6.4686

Epoch 43/300: 100%|██████████| 411/411 [01:02<00:00,  6.56it/s, D_loss=3.6923, G_loss=6.4909]

D_total: 4.3695, D_real: 0.2955, D_fake: 0.3098, D_gender: 0.3024, D_age: 7.6499
G_total: 5.6041, G_adv: 2.1733, G_gender: 0.2331, G_age: 6.4888

Epoch 44/300: 100%|██████████| 411/411 [01:01<00:00,  6.67it/s, D_loss=5.1796, G_loss=8.1149]

D_total: 4.4415, D_real: 0.3009, D_fake: 0.3179, D_gender: 0.2950, D_age: 7.7922
G_total: 5.6780, G_adv: 2.1802, G_gender: 0.2153, G_age: 6.6510

Epoch 45/300: 100%|██████████| 411/411 [01:08<00:00,  5.96it/s, D_loss=5.3926, G_loss=7.4169]

D_total: 4.4362, D_real: 0.3160, D_fake: 0.3367, D_gender: 0.2917, D_age: 7.7529
G_total: 5.6657, G_adv: 2.1590, G_gender: 0.2107, G_age: 6.6763
Saved checkpoint at epoch 45 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_45.pth

Epoch 46/300: 100%|██████████| 411/411 [01:03<00:00,  6.52it/s, D_loss=9.9466, G_loss=14.2080]

D_total: 4.3974, D_real: 0.3145, D_fake: 0.3334, D_gender: 0.2968, D_age: 7.6719
G_total: 5.6058, G_adv: 2.1608, G_gender: 0.2185, G_age: 6.5404

Epoch 47/300: 100%|██████████| 411/411 [01:02<00:00,  6.56it/s, D_loss=5.2799, G_loss=2.4024]

D_total: 4.2478, D_real: 0.3024, D_fake: 0.3276, D_gender: 0.2816, D_age: 7.4151
G_total: 5.5342, G_adv: 2.1872, G_gender: 0.2053, G_age: 6.3656

Epoch 48/300: 100%|██████████| 411/411 [01:02<00:00,  6.57it/s, D_loss=3.2357, G_loss=6.0838]

D_total: 4.4194, D_real: 0.2985, D_fake: 0.3177, D_gender: 0.2830, D_age: 7.7697
G_total: 5.7895, G_adv: 2.2333, G_gender: 0.2049, G_age: 6.7846

Epoch 49/300: 100%|██████████| 411/411 [01:03<00:00,  6.46it/s, D_loss=6.1001, G_loss=6.6539]

D_total: 4.3560, D_real: 0.2911, D_fake: 0.3184, D_gender: 0.2698, D_age: 7.6709
G_total: 5.7281, G_adv: 2.2447, G_gender: 0.1940, G_age: 6.6563

Epoch 50/300: 100%|██████████| 411/411 [01:08<00:00,  5.99it/s, D_loss=3.6685, G_loss=4.1491]

D_total: 4.3846, D_real: 0.3200, D_fake: 0.3413, D_gender: 0.2874, D_age: 7.6480
G_total: 5.6923, G_adv: 2.1509, G_gender: 0.2154, G_age: 6.7384
Saved checkpoint at epoch 50 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_50.pth

Epoch 51/300: 100%|██████████| 411/411 [01:01<00:00,  6.68it/s, D_loss=2.7644, G_loss=5.3347]

D_total: 4.3870, D_real: 0.2965, D_fake: 0.3124, D_gender: 0.2691, D_age: 7.7346
G_total: 5.7285, G_adv: 2.1803, G_gender: 0.1892, G_age: 6.7939

Epoch 52/300: 100%|██████████| 411/411 [01:01<00:00,  6.72it/s, D_loss=6.4261, G_loss=6.9632]

D_total: 4.2965, D_real: 0.2781, D_fake: 0.2929, D_gender: 0.2786, D_age: 7.5762
G_total: 5.8130, G_adv: 2.2883, G_gender: 0.2015, G_age: 6.7269

Epoch 53/300: 100%|██████████| 411/411 [01:03<00:00,  6.47it/s, D_loss=6.1286, G_loss=5.6969]

D_total: 4.3851, D_real: 0.2943, D_fake: 0.3197, D_gender: 0.2818, D_age: 7.7052
G_total: 5.7633, G_adv: 2.2308, G_gender: 0.2065, G_age: 6.7347

Epoch 54/300: 100%|██████████| 411/411 [01:04<00:00,  6.38it/s, D_loss=6.5483, G_loss=6.8514]

D_total: 4.4613, D_real: 0.3058, D_fake: 0.3153, D_gender: 0.2830, D_age: 7.8487
G_total: 5.7881, G_adv: 2.2487, G_gender: 0.2126, G_age: 6.7386

Epoch 55/300: 100%|██████████| 411/411 [01:08<00:00,  6.01it/s, D_loss=8.9641, G_loss=6.2793]

D_total: 4.6172, D_real: 0.2757, D_fake: 0.2970, D_gender: 0.2727, D_age: 8.2253
G_total: 6.3225, G_adv: 2.3960, G_gender: 0.2076, G_age: 7.5210
Saved checkpoint at epoch 55 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_55.pth

Epoch 56/300: 100%|██████████| 411/411 [01:03<00:00,  6.43it/s, D_loss=7.6746, G_loss=6.8665]

D_total: 4.6971, D_real: 0.3044, D_fake: 0.3228, D_gender: 0.2863, D_age: 8.3089
G_total: 6.1842, G_adv: 2.1648, G_gender: 0.2203, G_age: 7.6863

Epoch 57/300: 100%|██████████| 411/411 [01:03<00:00,  6.47it/s, D_loss=5.4465, G_loss=4.4576]

D_total: 4.6302, D_real: 0.3098, D_fake: 0.3253, D_gender: 0.2940, D_age: 8.1549
G_total: 6.1038, G_adv: 2.2115, G_gender: 0.2346, G_age: 7.4092

Epoch 58/300: 100%|██████████| 411/411 [01:03<00:00,  6.48it/s, D_loss=6.1703, G_loss=9.1892]

D_total: 4.4678, D_real: 0.2947, D_fake: 0.3160, D_gender: 0.2995, D_age: 7.8458
G_total: 5.9324, G_adv: 2.2164, G_gender: 0.2455, G_age: 7.0393

Epoch 59/300: 100%|██████████| 411/411 [01:02<00:00,  6.56it/s, D_loss=6.2357, G_loss=8.1474]

D_total: 4.6121, D_real: 0.3111, D_fake: 0.3226, D_gender: 0.2975, D_age: 8.1145
G_total: 6.0265, G_adv: 2.1666, G_gender: 0.2413, G_age: 7.3338

Epoch 60/300: 100%|██████████| 411/411 [01:07<00:00,  6.05it/s, D_loss=8.6921, G_loss=14.3293]

D_total: 4.5190, D_real: 0.2925, D_fake: 0.3094, D_gender: 0.2935, D_age: 7.9664
G_total: 5.9656, G_adv: 2.1933, G_gender: 0.2432, G_age: 7.1554
Saved checkpoint at epoch 60 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_60.pth

Epoch 61/300: 100%|██████████| 411/411 [01:03<00:00,  6.50it/s, D_loss=2.4334, G_loss=6.9039]

D_total: 4.4231, D_real: 0.2775, D_fake: 0.2945, D_gender: 0.2973, D_age: 7.7986
G_total: 5.9369, G_adv: 2.2671, G_gender: 0.2455, G_age: 6.9468

Epoch 62/300: 100%|██████████| 411/411 [01:06<00:00,  6.23it/s, D_loss=5.9859, G_loss=5.5564]

D_total: 4.4601, D_real: 0.2994, D_fake: 0.3267, D_gender: 0.2919, D_age: 7.8269
G_total: 5.8419, G_adv: 2.2049, G_gender: 0.2359, G_age: 6.8965

Epoch 63/300: 100%|██████████| 411/411 [01:03<00:00,  6.43it/s, D_loss=7.2552, G_loss=7.9674]

D_total: 4.5138, D_real: 0.3010, D_fake: 0.3230, D_gender: 0.2954, D_age: 7.9309
G_total: 5.8962, G_adv: 2.1671, G_gender: 0.2486, G_age: 7.0604

Epoch 64/300: 100%|██████████| 411/411 [01:03<00:00,  6.43it/s, D_loss=5.9662, G_loss=9.7621]

D_total: 4.4772, D_real: 0.3105, D_fake: 0.3253, D_gender: 0.2991, D_age: 7.8400
G_total: 5.8799, G_adv: 2.1704, G_gender: 0.2515, G_age: 7.0166

Epoch 65/300: 100%|██████████| 411/411 [01:09<00:00,  5.90it/s, D_loss=7.9481, G_loss=8.5531]

D_total: 4.5440, D_real: 0.3195, D_fake: 0.3387, D_gender: 0.3115, D_age: 7.9314
G_total: 5.8288, G_adv: 2.1570, G_gender: 0.2654, G_age: 6.9189
Saved checkpoint at epoch 65 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_65.pth

Epoch 66/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=4.4344, G_loss=6.4333]

D_total: 4.4918, D_real: 0.3151, D_fake: 0.3300, D_gender: 0.2965, D_age: 7.8640
G_total: 5.9076, G_adv: 2.1846, G_gender: 0.2416, G_age: 7.0595

Epoch 67/300: 100%|██████████| 411/411 [01:02<00:00,  6.57it/s, D_loss=7.3389, G_loss=9.3730]

D_total: 4.4001, D_real: 0.2902, D_fake: 0.3091, D_gender: 0.2906, D_age: 7.7360
G_total: 5.8216, G_adv: 2.1822, G_gender: 0.2350, G_age: 6.9027

Epoch 68/300: 100%|██████████| 411/411 [01:02<00:00,  6.54it/s, D_loss=7.1641, G_loss=13.9071]

D_total: 4.4496, D_real: 0.2997, D_fake: 0.3158, D_gender: 0.2976, D_age: 7.8075
G_total: 5.8593, G_adv: 2.1986, G_gender: 0.2430, G_age: 6.9325

Epoch 69/300: 100%|██████████| 411/411 [01:02<00:00,  6.60it/s, D_loss=3.4576, G_loss=7.0299]

D_total: 4.3300, D_real: 0.2728, D_fake: 0.2840, D_gender: 0.2926, D_age: 7.6350
G_total: 5.8343, G_adv: 2.2703, G_gender: 0.2382, G_age: 6.7468

Epoch 70/300: 100%|██████████| 411/411 [01:08<00:00,  6.00it/s, D_loss=8.1984, G_loss=12.3686]

D_total: 4.2844, D_real: 0.2756, D_fake: 0.2932, D_gender: 0.2796, D_age: 7.5527
G_total: 5.8553, G_adv: 2.2496, G_gender: 0.2213, G_age: 6.8572
Saved checkpoint at epoch 70 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_70.pth

Epoch 71/300: 100%|██████████| 411/411 [01:03<00:00,  6.51it/s, D_loss=5.4188, G_loss=5.1514]

D_total: 4.4596, D_real: 0.3108, D_fake: 0.3303, D_gender: 0.2756, D_age: 7.8370
G_total: 5.8874, G_adv: 2.1857, G_gender: 0.2220, G_age: 7.0482

Epoch 72/300: 100%|██████████| 411/411 [01:03<00:00,  6.47it/s, D_loss=6.9069, G_loss=7.9973]

D_total: 4.3305, D_real: 0.2982, D_fake: 0.3216, D_gender: 0.2825, D_age: 7.5893
G_total: 5.8052, G_adv: 2.2118, G_gender: 0.2226, G_age: 6.8307

Epoch 73/300: 100%|██████████| 411/411 [01:02<00:00,  6.53it/s, D_loss=3.8994, G_loss=5.6526]

D_total: 4.4037, D_real: 0.3032, D_fake: 0.3101, D_gender: 0.2793, D_age: 7.7472
G_total: 5.8321, G_adv: 2.2014, G_gender: 0.2273, G_age: 6.8977

Epoch 74/300: 100%|██████████| 411/411 [01:03<00:00,  6.45it/s, D_loss=3.6403, G_loss=4.6703]

D_total: 4.2979, D_real: 0.2889, D_fake: 0.3002, D_gender: 0.2838, D_age: 7.5525
G_total: 5.8050, G_adv: 2.2333, G_gender: 0.2233, G_age: 6.7863

Epoch 75/300: 100%|██████████| 411/411 [01:09<00:00,  5.91it/s, D_loss=4.7244, G_loss=7.3119]

D_total: 4.3213, D_real: 0.2894, D_fake: 0.3137, D_gender: 0.2774, D_age: 7.5957
G_total: 5.8500, G_adv: 2.2474, G_gender: 0.2223, G_age: 6.8495
Saved checkpoint at epoch 75 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_75.pth

Epoch 76/300: 100%|██████████| 411/411 [01:05<00:00,  6.31it/s, D_loss=3.0436, G_loss=11.9783]

D_total: 4.3775, D_real: 0.3141, D_fake: 0.3306, D_gender: 0.2809, D_age: 7.6608
G_total: 5.8226, G_adv: 2.2370, G_gender: 0.2288, G_age: 6.8051

Epoch 77/300: 100%|██████████| 411/411 [01:03<00:00,  6.46it/s, D_loss=3.7075, G_loss=5.2161]

D_total: 4.3758, D_real: 0.3118, D_fake: 0.3237, D_gender: 0.2775, D_age: 7.6722
G_total: 5.7543, G_adv: 2.1648, G_gender: 0.2203, G_age: 6.8265

Epoch 78/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=3.7030, G_loss=6.8890]

D_total: 4.3297, D_real: 0.3026, D_fake: 0.3226, D_gender: 0.2893, D_age: 7.5711
G_total: 5.7988, G_adv: 2.2176, G_gender: 0.2281, G_age: 6.7973

Epoch 79/300: 100%|██████████| 411/411 [01:04<00:00,  6.37it/s, D_loss=8.8862, G_loss=12.1925]

D_total: 4.3229, D_real: 0.3026, D_fake: 0.3123, D_gender: 0.2760, D_age: 7.5894
G_total: 5.8202, G_adv: 2.2137, G_gender: 0.2156, G_age: 6.8681

Epoch 80/300: 100%|██████████| 411/411 [01:09<00:00,  5.89it/s, D_loss=3.2071, G_loss=7.3980]

D_total: 4.2612, D_real: 0.2950, D_fake: 0.3154, D_gender: 0.2738, D_age: 7.4739
G_total: 5.6485, G_adv: 2.1855, G_gender: 0.2181, G_age: 6.5769
Saved checkpoint at epoch 80 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_80.pth

Epoch 81/300: 100%|██████████| 411/411 [01:02<00:00,  6.57it/s, D_loss=6.1701, G_loss=6.9507]

D_total: 4.2908, D_real: 0.3070, D_fake: 0.3218, D_gender: 0.2730, D_age: 7.5159
G_total: 5.7384, G_adv: 2.1885, G_gender: 0.2187, G_age: 6.7500

Epoch 82/300: 100%|██████████| 411/411 [01:04<00:00,  6.34it/s, D_loss=6.2108, G_loss=5.8531]

D_total: 4.2706, D_real: 0.3079, D_fake: 0.3341, D_gender: 0.2768, D_age: 7.4563
G_total: 5.7230, G_adv: 2.2181, G_gender: 0.2291, G_age: 6.6433

Epoch 83/300: 100%|██████████| 411/411 [01:04<00:00,  6.39it/s, D_loss=5.5313, G_loss=6.9309]

D_total: 4.2567, D_real: 0.3150, D_fake: 0.3273, D_gender: 0.2673, D_age: 7.4435
G_total: 5.6579, G_adv: 2.1756, G_gender: 0.2118, G_age: 6.6258

Epoch 84/300: 100%|██████████| 411/411 [01:02<00:00,  6.61it/s, D_loss=6.0136, G_loss=7.3674]

D_total: 4.3136, D_real: 0.3078, D_fake: 0.3195, D_gender: 0.2712, D_age: 7.5659
G_total: 5.6286, G_adv: 2.1694, G_gender: 0.2112, G_age: 6.5806

Epoch 85/300: 100%|██████████| 411/411 [01:12<00:00,  5.69it/s, D_loss=7.6664, G_loss=3.5787]

D_total: 4.3070, D_real: 0.3179, D_fake: 0.3378, D_gender: 0.2752, D_age: 7.5181
G_total: 5.7380, G_adv: 2.2025, G_gender: 0.2206, G_age: 6.7179
Saved checkpoint at epoch 85 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_85.pth

Epoch 86/300: 100%|██████████| 411/411 [01:04<00:00,  6.39it/s, D_loss=9.1301, G_loss=7.9431]

D_total: 4.2397, D_real: 0.2986, D_fake: 0.3205, D_gender: 0.2722, D_age: 7.4249
G_total: 5.6818, G_adv: 2.1747, G_gender: 0.2149, G_age: 6.6702

Epoch 87/300: 100%|██████████| 411/411 [01:04<00:00,  6.35it/s, D_loss=2.6237, G_loss=9.2945]

D_total: 4.2541, D_real: 0.3239, D_fake: 0.3307, D_gender: 0.2648, D_age: 7.4298
G_total: 5.6322, G_adv: 2.1412, G_gender: 0.2134, G_age: 6.6406

Epoch 88/300: 100%|██████████| 411/411 [01:03<00:00,  6.51it/s, D_loss=4.7245, G_loss=9.7201]

D_total: 4.1488, D_real: 0.2869, D_fake: 0.3096, D_gender: 0.2647, D_age: 7.2777
G_total: 5.6689, G_adv: 2.2327, G_gender: 0.2198, G_age: 6.5207

Epoch 89/300: 100%|██████████| 411/411 [01:00<00:00,  6.76it/s, D_loss=3.2813, G_loss=10.1981]

D_total: 4.2736, D_real: 0.3165, D_fake: 0.3304, D_gender: 0.2725, D_age: 7.4644
G_total: 5.6656, G_adv: 2.1795, G_gender: 0.2201, G_age: 6.6200

Epoch 90/300: 100%|██████████| 411/411 [01:10<00:00,  5.87it/s, D_loss=3.4916, G_loss=5.0187]

D_total: 4.2688, D_real: 0.3092, D_fake: 0.3238, D_gender: 0.2652, D_age: 7.4803
G_total: 5.6239, G_adv: 2.1558, G_gender: 0.2112, G_age: 6.5983
Saved checkpoint at epoch 90 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_90.pth

Epoch 91/300: 100%|██████████| 411/411 [01:03<00:00,  6.47it/s, D_loss=6.5259, G_loss=6.4893]

D_total: 4.2311, D_real: 0.3180, D_fake: 0.3230, D_gender: 0.2601, D_age: 7.4051
G_total: 5.6152, G_adv: 2.1832, G_gender: 0.2027, G_age: 6.5396

Epoch 92/300: 100%|██████████| 411/411 [01:04<00:00,  6.40it/s, D_loss=6.9673, G_loss=8.5667]

D_total: 4.1564, D_real: 0.2905, D_fake: 0.3127, D_gender: 0.2613, D_age: 7.2914
G_total: 5.6178, G_adv: 2.2153, G_gender: 0.2018, G_age: 6.4823

Epoch 93/300: 100%|██████████| 411/411 [01:04<00:00,  6.41it/s, D_loss=2.4882, G_loss=12.3477]

D_total: 4.2421, D_real: 0.3206, D_fake: 0.3442, D_gender: 0.2565, D_age: 7.4090
G_total: 5.5954, G_adv: 2.1925, G_gender: 0.2007, G_age: 6.4846

Epoch 94/300: 100%|██████████| 411/411 [01:04<00:00,  6.37it/s, D_loss=6.9071, G_loss=6.6976]

D_total: 4.1827, D_real: 0.3148, D_fake: 0.3308, D_gender: 0.2671, D_age: 7.2925
G_total: 5.4953, G_adv: 2.1280, G_gender: 0.2069, G_age: 6.4036

Epoch 95/300: 100%|██████████| 411/411 [01:11<00:00,  5.77it/s, D_loss=7.6376, G_loss=8.1299]

D_total: 4.1622, D_real: 0.3027, D_fake: 0.3216, D_gender: 0.2615, D_age: 7.2818
G_total: 5.6330, G_adv: 2.2269, G_gender: 0.2051, G_age: 6.4841
Saved checkpoint at epoch 95 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_95.pth

Epoch 96/300: 100%|██████████| 411/411 [01:06<00:00,  6.19it/s, D_loss=5.9209, G_loss=10.6979]

D_total: 4.1190, D_real: 0.3025, D_fake: 0.3089, D_gender: 0.2571, D_age: 7.2154
G_total: 5.5745, G_adv: 2.1948, G_gender: 0.2018, G_age: 6.4364

Epoch 97/300: 100%|██████████| 411/411 [01:05<00:00,  6.28it/s, D_loss=4.0704, G_loss=7.5332]

D_total: 4.2267, D_real: 0.3126, D_fake: 0.3274, D_gender: 0.2703, D_age: 7.3809
G_total: 5.5674, G_adv: 2.1976, G_gender: 0.2164, G_age: 6.3933

Epoch 98/300: 100%|██████████| 411/411 [01:06<00:00,  6.20it/s, D_loss=8.5846, G_loss=11.8156]

D_total: 4.2578, D_real: 0.3072, D_fake: 0.3267, D_gender: 0.2665, D_age: 7.4554
G_total: 5.6364, G_adv: 2.2034, G_gender: 0.2167, G_age: 6.5194

Epoch 99/300: 100%|██████████| 411/411 [01:04<00:00,  6.37it/s, D_loss=7.1924, G_loss=9.3649]

D_total: 4.1758, D_real: 0.3216, D_fake: 0.3429, D_gender: 0.2541, D_age: 7.2807
G_total: 5.5139, G_adv: 2.1688, G_gender: 0.2000, G_age: 6.3701

Epoch 100/300: 100%|██████████| 411/411 [01:12<00:00,  5.68it/s, D_loss=5.0373, G_loss=3.9704]

D_total: 4.1818, D_real: 0.2941, D_fake: 0.3280, D_gender: 0.2681, D_age: 7.3125
G_total: 5.6409, G_adv: 2.2534, G_gender: 0.2034, G_age: 6.4496
Saved checkpoint at epoch 100 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_100.pth

Epoch 101/300: 100%|██████████| 411/411 [01:04<00:00,  6.39it/s, D_loss=5.3671, G_loss=11.1556]

D_total: 4.2530, D_real: 0.3174, D_fake: 0.3353, D_gender: 0.2671, D_age: 7.4260
G_total: 5.6466, G_adv: 2.1794, G_gender: 0.2095, G_age: 6.5991

Epoch 102/300: 100%|██████████| 411/411 [01:05<00:00,  6.29it/s, D_loss=9.6036, G_loss=15.2049]

D_total: 4.1442, D_real: 0.3106, D_fake: 0.3366, D_gender: 0.2482, D_age: 7.2442
G_total: 5.5318, G_adv: 2.2130, G_gender: 0.1893, G_age: 6.3347

Epoch 103/300: 100%|██████████| 411/411 [01:04<00:00,  6.32it/s, D_loss=4.2995, G_loss=5.2473]

D_total: 4.1959, D_real: 0.3118, D_fake: 0.3201, D_gender: 0.2411, D_age: 7.3741
G_total: 5.6140, G_adv: 2.2482, G_gender: 0.1922, G_age: 6.4240

Epoch 104/300: 100%|██████████| 411/411 [01:06<00:00,  6.22it/s, D_loss=7.0001, G_loss=9.1284]

D_total: 4.1333, D_real: 0.3053, D_fake: 0.3179, D_gender: 0.2389, D_age: 7.2611
G_total: 5.6120, G_adv: 2.2492, G_gender: 0.1786, G_age: 6.4396

Epoch 105/300: 100%|██████████| 411/411 [01:10<00:00,  5.80it/s, D_loss=5.2061, G_loss=7.3198]

D_total: 4.1616, D_real: 0.3278, D_fake: 0.3395, D_gender: 0.2481, D_age: 7.2589
G_total: 5.5356, G_adv: 2.2306, G_gender: 0.1949, G_age: 6.2982
Saved checkpoint at epoch 105 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_105.pth

Epoch 106/300: 100%|██████████| 411/411 [01:05<00:00,  6.30it/s, D_loss=8.6933, G_loss=7.7608]

D_total: 4.0719, D_real: 0.3058, D_fake: 0.3240, D_gender: 0.2447, D_age: 7.1224
G_total: 5.5099, G_adv: 2.2110, G_gender: 0.1860, G_age: 6.3002

Epoch 107/300: 100%|██████████| 411/411 [01:05<00:00,  6.26it/s, D_loss=4.2366, G_loss=9.8714]

D_total: 4.2141, D_real: 0.3214, D_fake: 0.3345, D_gender: 0.2450, D_age: 7.3802
G_total: 5.5484, G_adv: 2.1907, G_gender: 0.1899, G_age: 6.4116

Epoch 108/300: 100%|██████████| 411/411 [01:05<00:00,  6.25it/s, D_loss=3.6892, G_loss=8.0859]

D_total: 4.1803, D_real: 0.3279, D_fake: 0.3547, D_gender: 0.2366, D_age: 7.2995
G_total: 5.5625, G_adv: 2.1890, G_gender: 0.1835, G_age: 6.4534

Epoch 109/300: 100%|██████████| 411/411 [01:05<00:00,  6.31it/s, D_loss=6.3619, G_loss=5.6384]

D_total: 4.1147, D_real: 0.3276, D_fake: 0.3393, D_gender: 0.2435, D_age: 7.1729
G_total: 5.4443, G_adv: 2.2080, G_gender: 0.1776, G_age: 6.1883

Epoch 110/300: 100%|██████████| 411/411 [01:09<00:00,  5.90it/s, D_loss=3.9795, G_loss=9.7067]

D_total: 4.0979, D_real: 0.3196, D_fake: 0.3354, D_gender: 0.2264, D_age: 7.1786
G_total: 5.5321, G_adv: 2.2307, G_gender: 0.1694, G_age: 6.3318
Saved checkpoint at epoch 110 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_110.pth

Epoch 111/300: 100%|██████████| 411/411 [01:04<00:00,  6.39it/s, D_loss=3.7411, G_loss=6.7749]

D_total: 4.1052, D_real: 0.3289, D_fake: 0.3496, D_gender: 0.2375, D_age: 7.1518
G_total: 5.4061, G_adv: 2.1810, G_gender: 0.1814, G_age: 6.1599

Epoch 112/300: 100%|██████████| 411/411 [01:02<00:00,  6.55it/s, D_loss=4.1086, G_loss=9.7111]

D_total: 4.1958, D_real: 0.3249, D_fake: 0.3415, D_gender: 0.2434, D_age: 7.3357
G_total: 5.5772, G_adv: 2.1863, G_gender: 0.1832, G_age: 6.4885

Epoch 113/300: 100%|██████████| 411/411 [01:03<00:00,  6.45it/s, D_loss=4.6520, G_loss=5.3117]

D_total: 4.2020, D_real: 0.3307, D_fake: 0.3423, D_gender: 0.2245, D_age: 7.3718
G_total: 5.4994, G_adv: 2.1963, G_gender: 0.1646, G_age: 6.3428

Epoch 114/300: 100%|██████████| 411/411 [01:04<00:00,  6.37it/s, D_loss=4.1498, G_loss=8.0391]

D_total: 4.0834, D_real: 0.3255, D_fake: 0.3443, D_gender: 0.2283, D_age: 7.1318
G_total: 5.3347, G_adv: 2.0980, G_gender: 0.1686, G_age: 6.2037

Epoch 115/300: 100%|██████████| 411/411 [01:13<00:00,  5.58it/s, D_loss=3.9104, G_loss=7.0045]

D_total: 4.0940, D_real: 0.3217, D_fake: 0.3405, D_gender: 0.2276, D_age: 7.1616
G_total: 5.4503, G_adv: 2.2165, G_gender: 0.1663, G_age: 6.2015
Saved checkpoint at epoch 115 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_115.pth

Epoch 116/300: 100%|██████████| 411/411 [01:04<00:00,  6.40it/s, D_loss=3.7122, G_loss=4.3242]

D_total: 4.0390, D_real: 0.3178, D_fake: 0.3346, D_gender: 0.2118, D_age: 7.0866
G_total: 5.4043, G_adv: 2.1628, G_gender: 0.1591, G_age: 6.2286

Epoch 117/300: 100%|██████████| 411/411 [01:04<00:00,  6.33it/s, D_loss=4.5721, G_loss=4.5006]

D_total: 4.1107, D_real: 0.3220, D_fake: 0.3383, D_gender: 0.2166, D_age: 7.2146
G_total: 5.5116, G_adv: 2.2211, G_gender: 0.1544, G_age: 6.3339

Epoch 118/300: 100%|██████████| 411/411 [01:04<00:00,  6.38it/s, D_loss=7.7764, G_loss=9.8315]

D_total: 4.0329, D_real: 0.3051, D_fake: 0.3275, D_gender: 0.2223, D_age: 7.0776
G_total: 5.4245, G_adv: 2.2271, G_gender: 0.1666, G_age: 6.1284

Epoch 119/300: 100%|██████████| 411/411 [01:04<00:00,  6.36it/s, D_loss=4.0729, G_loss=7.3423]

D_total: 3.9979, D_real: 0.2913, D_fake: 0.3001, D_gender: 0.2084, D_age: 7.0709
G_total: 5.4127, G_adv: 2.2405, G_gender: 0.1442, G_age: 6.1137

Epoch 120/300: 100%|██████████| 411/411 [01:11<00:00,  5.73it/s, D_loss=6.4755, G_loss=10.8292]

D_total: 4.0500, D_real: 0.3086, D_fake: 0.3183, D_gender: 0.2141, D_age: 7.1305
G_total: 5.5217, G_adv: 2.2660, G_gender: 0.1571, G_age: 6.2599
Saved checkpoint at epoch 120 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_120.pth

Epoch 121/300: 100%|██████████| 411/411 [01:04<00:00,  6.35it/s, D_loss=3.6637, G_loss=6.1255]

D_total: 3.9478, D_real: 0.3187, D_fake: 0.3437, D_gender: 0.2183, D_age: 6.8839
G_total: 5.4043, G_adv: 2.2510, G_gender: 0.1616, G_age: 6.0479

Epoch 122/300: 100%|██████████| 411/411 [01:04<00:00,  6.33it/s, D_loss=8.1310, G_loss=10.7064]

D_total: 4.1067, D_real: 0.3283, D_fake: 0.3424, D_gender: 0.2193, D_age: 7.1919
G_total: 5.4489, G_adv: 2.1960, G_gender: 0.1550, G_age: 6.2577

Epoch 123/300: 100%|██████████| 411/411 [01:04<00:00,  6.34it/s, D_loss=4.9213, G_loss=5.9557]

D_total: 4.1435, D_real: 0.3519, D_fake: 0.3541, D_gender: 0.2191, D_age: 7.2305
G_total: 5.4484, G_adv: 2.1781, G_gender: 0.1476, G_age: 6.3044

Epoch 124/300: 100%|██████████| 411/411 [01:03<00:00,  6.45it/s, D_loss=5.5968, G_loss=7.2346]

D_total: 4.0379, D_real: 0.3054, D_fake: 0.3271, D_gender: 0.2037, D_age: 7.1176
G_total: 5.3776, G_adv: 2.2101, G_gender: 0.1412, G_age: 6.1089

Epoch 125/300: 100%|██████████| 411/411 [01:10<00:00,  5.85it/s, D_loss=4.4981, G_loss=6.7255]

D_total: 4.2108, D_real: 0.3464, D_fake: 0.3497, D_gender: 0.2050, D_age: 7.3974
G_total: 5.5110, G_adv: 2.1808, G_gender: 0.1449, G_age: 6.4285
Saved checkpoint at epoch 125 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_125.pth

Epoch 126/300: 100%|██████████| 411/411 [01:05<00:00,  6.28it/s, D_loss=4.7223, G_loss=6.7447]

D_total: 4.1591, D_real: 0.3302, D_fake: 0.3549, D_gender: 0.2134, D_age: 7.2917
G_total: 5.4193, G_adv: 2.1738, G_gender: 0.1495, G_age: 6.2518

Epoch 127/300: 100%|██████████| 411/411 [01:03<00:00,  6.46it/s, D_loss=4.3992, G_loss=6.8635]

D_total: 4.0525, D_real: 0.3132, D_fake: 0.3320, D_gender: 0.2131, D_age: 7.1189
G_total: 5.4498, G_adv: 2.1971, G_gender: 0.1499, G_age: 6.2657

Epoch 128/300: 100%|██████████| 411/411 [01:01<00:00,  6.67it/s, D_loss=6.3163, G_loss=8.5549]

D_total: 4.1024, D_real: 0.3086, D_fake: 0.3267, D_gender: 0.2164, D_age: 7.2232
G_total: 5.5616, G_adv: 2.2585, G_gender: 0.1496, G_age: 6.3669

Epoch 129/300: 100%|██████████| 411/411 [01:03<00:00,  6.45it/s, D_loss=4.1039, G_loss=4.8090]

D_total: 4.1437, D_real: 0.3351, D_fake: 0.3561, D_gender: 0.2124, D_age: 7.2562
G_total: 5.4427, G_adv: 2.1379, G_gender: 0.1508, G_age: 6.3681

Epoch 130/300: 100%|██████████| 411/411 [01:07<00:00,  6.11it/s, D_loss=3.5213, G_loss=5.8594]

D_total: 4.0996, D_real: 0.3338, D_fake: 0.3487, D_gender: 0.2113, D_age: 7.1785
G_total: 5.3948, G_adv: 2.1825, G_gender: 0.1500, G_age: 6.1847
Saved checkpoint at epoch 130 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_130.pth

Epoch 131/300: 100%|██████████| 411/411 [01:01<00:00,  6.69it/s, D_loss=9.2040, G_loss=6.9773]

D_total: 4.1421, D_real: 0.3285, D_fake: 0.3574, D_gender: 0.2102, D_age: 7.2619
G_total: 5.4938, G_adv: 2.1800, G_gender: 0.1536, G_age: 6.3818

Epoch 132/300: 100%|██████████| 411/411 [01:01<00:00,  6.66it/s, D_loss=3.1915, G_loss=5.7669]

D_total: 4.0707, D_real: 0.3345, D_fake: 0.3522, D_gender: 0.2079, D_age: 7.1220
G_total: 5.3758, G_adv: 2.2136, G_gender: 0.1529, G_age: 6.0797

Epoch 133/300: 100%|██████████| 411/411 [01:05<00:00,  6.32it/s, D_loss=3.5252, G_loss=7.8366]

D_total: 3.9447, D_real: 0.2993, D_fake: 0.3186, D_gender: 0.1994, D_age: 6.9526
G_total: 5.4359, G_adv: 2.2356, G_gender: 0.1511, G_age: 6.1587

Epoch 134/300: 100%|██████████| 411/411 [01:06<00:00,  6.16it/s, D_loss=8.1240, G_loss=10.0172]

D_total: 4.1938, D_real: 0.3307, D_fake: 0.3439, D_gender: 0.2003, D_age: 7.3925
G_total: 5.5992, G_adv: 2.1712, G_gender: 0.1450, G_age: 6.6239

Epoch 135/300: 100%|██████████| 411/411 [01:08<00:00,  6.03it/s, D_loss=3.6413, G_loss=8.4348]

D_total: 4.0750, D_real: 0.3279, D_fake: 0.3457, D_gender: 0.2105, D_age: 7.1397
G_total: 5.4165, G_adv: 2.2184, G_gender: 0.1544, G_age: 6.1491
Saved checkpoint at epoch 135 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_135.pth

Epoch 136/300: 100%|██████████| 411/411 [01:04<00:00,  6.39it/s, D_loss=4.7631, G_loss=12.8550]

D_total: 4.0135, D_real: 0.3294, D_fake: 0.3383, D_gender: 0.2071, D_age: 7.0278
G_total: 5.4012, G_adv: 2.2064, G_gender: 0.1408, G_age: 6.1644

Epoch 137/300: 100%|██████████| 411/411 [01:04<00:00,  6.33it/s, D_loss=2.7543, G_loss=5.5120]

D_total: 4.1141, D_real: 0.3308, D_fake: 0.3462, D_gender: 0.1981, D_age: 7.2342
G_total: 5.4036, G_adv: 2.1820, G_gender: 0.1348, G_age: 6.2275

Epoch 138/300: 100%|██████████| 411/411 [01:04<00:00,  6.32it/s, D_loss=2.6560, G_loss=4.8243]

D_total: 4.0553, D_real: 0.3315, D_fake: 0.3384, D_gender: 0.2042, D_age: 7.1141
G_total: 5.4572, G_adv: 2.2256, G_gender: 0.1431, G_age: 6.2343

Epoch 139/300: 100%|██████████| 411/411 [01:06<00:00,  6.19it/s, D_loss=4.4188, G_loss=8.0115]

D_total: 4.0444, D_real: 0.3268, D_fake: 0.3529, D_gender: 0.2094, D_age: 7.0740
G_total: 5.4574, G_adv: 2.1975, G_gender: 0.1489, G_age: 6.2816

Epoch 140/300: 100%|██████████| 411/411 [01:10<00:00,  5.79it/s, D_loss=4.8298, G_loss=5.7748]

D_total: 4.0945, D_real: 0.3363, D_fake: 0.3474, D_gender: 0.2132, D_age: 7.1642
G_total: 5.3647, G_adv: 2.1652, G_gender: 0.1549, G_age: 6.1512
Saved checkpoint at epoch 140 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_140.pth

Epoch 141/300: 100%|██████████| 411/411 [01:03<00:00,  6.46it/s, D_loss=2.7436, G_loss=8.6540]

D_total: 3.9534, D_real: 0.3259, D_fake: 0.3468, D_gender: 0.2051, D_age: 6.9058
G_total: 5.3138, G_adv: 2.1754, G_gender: 0.1466, G_age: 6.0424

Epoch 142/300: 100%|██████████| 411/411 [01:03<00:00,  6.43it/s, D_loss=3.5020, G_loss=9.6151]

D_total: 4.0371, D_real: 0.3286, D_fake: 0.3405, D_gender: 0.1957, D_age: 7.0921
G_total: 5.4617, G_adv: 2.1794, G_gender: 0.1299, G_age: 6.3569

Epoch 143/300: 100%|██████████| 411/411 [01:04<00:00,  6.41it/s, D_loss=2.1276, G_loss=2.5183]

D_total: 4.0925, D_real: 0.3338, D_fake: 0.3468, D_gender: 0.1895, D_age: 7.2011
G_total: 5.3839, G_adv: 2.1322, G_gender: 0.1360, G_age: 6.2859

Epoch 144/300: 100%|██████████| 411/411 [01:07<00:00,  6.08it/s, D_loss=5.9145, G_loss=6.3257]

D_total: 4.0410, D_real: 0.3260, D_fake: 0.3401, D_gender: 0.2000, D_age: 7.0958
G_total: 5.3717, G_adv: 2.1863, G_gender: 0.1408, G_age: 6.1455

Epoch 145/300: 100%|██████████| 411/411 [01:11<00:00,  5.76it/s, D_loss=4.9855, G_loss=6.9657]

D_total: 4.0231, D_real: 0.3204, D_fake: 0.3448, D_gender: 0.2032, D_age: 7.0559
G_total: 5.3343, G_adv: 2.1872, G_gender: 0.1466, G_age: 6.0596
Saved checkpoint at epoch 145 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_145.pth

Epoch 146/300: 100%|██████████| 411/411 [01:06<00:00,  6.20it/s, D_loss=3.4184, G_loss=6.4150]

D_total: 4.0757, D_real: 0.3348, D_fake: 0.3485, D_gender: 0.2009, D_age: 7.1467
G_total: 5.4022, G_adv: 2.1860, G_gender: 0.1422, G_age: 6.2049

Epoch 147/300: 100%|██████████| 411/411 [01:06<00:00,  6.19it/s, D_loss=3.8508, G_loss=5.9762]

D_total: 3.9900, D_real: 0.3193, D_fake: 0.3262, D_gender: 0.2020, D_age: 7.0112
G_total: 5.3780, G_adv: 2.2339, G_gender: 0.1470, G_age: 6.0529

Epoch 148/300: 100%|██████████| 411/411 [01:03<00:00,  6.45it/s, D_loss=4.6318, G_loss=7.1978]

D_total: 4.1284, D_real: 0.3557, D_fake: 0.3811, D_gender: 0.1974, D_age: 7.2040
G_total: 5.4338, G_adv: 2.1567, G_gender: 0.1313, G_age: 6.3440

Epoch 149/300: 100%|██████████| 411/411 [01:03<00:00,  6.46it/s, D_loss=3.2280, G_loss=8.2135]

D_total: 4.0915, D_real: 0.3305, D_fake: 0.3410, D_gender: 0.1971, D_age: 7.1962
G_total: 5.4243, G_adv: 2.2104, G_gender: 0.1378, G_age: 6.2074

Epoch 150/300: 100%|██████████| 411/411 [01:13<00:00,  5.59it/s, D_loss=4.0005, G_loss=3.2849]

D_total: 4.0362, D_real: 0.3411, D_fake: 0.3571, D_gender: 0.1971, D_age: 7.0588
G_total: 5.3853, G_adv: 2.1695, G_gender: 0.1411, G_age: 6.2059
Saved checkpoint at epoch 150 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_150.pth

Epoch 151/300: 100%|██████████| 411/411 [01:04<00:00,  6.36it/s, D_loss=5.4564, G_loss=10.3787]

D_total: 3.9877, D_real: 0.3338, D_fake: 0.3503, D_gender: 0.1991, D_age: 6.9726
G_total: 5.3751, G_adv: 2.2166, G_gender: 0.1332, G_age: 6.1040

Epoch 152/300: 100%|██████████| 411/411 [01:04<00:00,  6.34it/s, D_loss=2.6268, G_loss=11.0589]

D_total: 3.9712, D_real: 0.3200, D_fake: 0.3306, D_gender: 0.1912, D_age: 6.9859
G_total: 5.3957, G_adv: 2.2108, G_gender: 0.1382, G_age: 6.1486

Epoch 153/300: 100%|██████████| 411/411 [01:02<00:00,  6.55it/s, D_loss=2.9828, G_loss=8.8782]

D_total: 3.9723, D_real: 0.3250, D_fake: 0.3471, D_gender: 0.1899, D_age: 6.9687
G_total: 5.3283, G_adv: 2.1727, G_gender: 0.1330, G_age: 6.0983

Epoch 154/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=5.6936, G_loss=7.8406]

D_total: 3.9576, D_real: 0.3239, D_fake: 0.3495, D_gender: 0.1868, D_age: 6.9428
G_total: 5.4087, G_adv: 2.2502, G_gender: 0.1310, G_age: 6.1074

Epoch 155/300: 100%|██████████| 411/411 [01:09<00:00,  5.95it/s, D_loss=2.6402, G_loss=4.9232]

D_total: 3.9942, D_real: 0.3381, D_fake: 0.3503, D_gender: 0.1901, D_age: 6.9958
G_total: 5.4135, G_adv: 2.1871, G_gender: 0.1314, G_age: 6.2427
Saved checkpoint at epoch 155 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_155.pth

Epoch 156/300: 100%|██████████| 411/411 [01:02<00:00,  6.53it/s, D_loss=3.8679, G_loss=10.0038]

D_total: 4.1087, D_real: 0.3408, D_fake: 0.3566, D_gender: 0.1842, D_age: 7.2253
G_total: 5.3618, G_adv: 2.1502, G_gender: 0.1270, G_age: 6.2200

Epoch 157/300: 100%|██████████| 411/411 [01:04<00:00,  6.41it/s, D_loss=5.8392, G_loss=8.4379]

D_total: 4.0057, D_real: 0.3436, D_fake: 0.3598, D_gender: 0.1908, D_age: 7.0026
G_total: 5.3472, G_adv: 2.2146, G_gender: 0.1294, G_age: 6.0581

Epoch 158/300: 100%|██████████| 411/411 [01:02<00:00,  6.59it/s, D_loss=4.8769, G_loss=7.1862]

D_total: 3.9193, D_real: 0.3142, D_fake: 0.3254, D_gender: 0.1865, D_age: 6.9006
G_total: 5.3990, G_adv: 2.2450, G_gender: 0.1285, G_age: 6.1023

Epoch 159/300: 100%|██████████| 411/411 [01:02<00:00,  6.57it/s, D_loss=3.8128, G_loss=12.4199]

D_total: 4.0328, D_real: 0.3346, D_fake: 0.3548, D_gender: 0.1895, D_age: 7.0731
G_total: 5.3784, G_adv: 2.1920, G_gender: 0.1335, G_age: 6.1591

Epoch 160/300: 100%|██████████| 411/411 [01:07<00:00,  6.07it/s, D_loss=4.1971, G_loss=6.0130]

D_total: 4.0263, D_real: 0.3224, D_fake: 0.3390, D_gender: 0.1874, D_age: 7.0914
G_total: 5.3709, G_adv: 2.1588, G_gender: 0.1288, G_age: 6.2182
Saved checkpoint at epoch 160 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_160.pth

Epoch 161/300: 100%|██████████| 411/411 [01:02<00:00,  6.55it/s, D_loss=7.2313, G_loss=9.4550]

D_total: 4.1366, D_real: 0.3414, D_fake: 0.3566, D_gender: 0.1886, D_age: 7.2735
G_total: 5.4261, G_adv: 2.1798, G_gender: 0.1308, G_age: 6.2833

Epoch 162/300: 100%|██████████| 411/411 [01:00<00:00,  6.75it/s, D_loss=6.7729, G_loss=9.4420]

D_total: 4.0359, D_real: 0.3323, D_fake: 0.3529, D_gender: 0.1893, D_age: 7.0836
G_total: 5.3553, G_adv: 2.1823, G_gender: 0.1277, G_age: 6.1415

Epoch 163/300: 100%|██████████| 411/411 [01:04<00:00,  6.41it/s, D_loss=7.6509, G_loss=8.7240]

D_total: 3.9780, D_real: 0.3323, D_fake: 0.3576, D_gender: 0.1866, D_age: 6.9675
G_total: 5.3569, G_adv: 2.2147, G_gender: 0.1307, G_age: 6.0754

Epoch 164/300: 100%|██████████| 411/411 [01:03<00:00,  6.48it/s, D_loss=4.6375, G_loss=6.6444]

D_total: 3.9424, D_real: 0.3240, D_fake: 0.3405, D_gender: 0.1878, D_age: 6.9198
G_total: 5.3938, G_adv: 2.2107, G_gender: 0.1331, G_age: 6.1534

Epoch 165/300: 100%|██████████| 411/411 [01:07<00:00,  6.10it/s, D_loss=4.5269, G_loss=12.2463]

D_total: 3.9416, D_real: 0.3279, D_fake: 0.3334, D_gender: 0.1845, D_age: 6.9267
G_total: 5.3558, G_adv: 2.2021, G_gender: 0.1276, G_age: 6.1031
Saved checkpoint at epoch 165 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_165.pth

Epoch 166/300: 100%|██████████| 411/411 [01:03<00:00,  6.50it/s, D_loss=5.0932, G_loss=8.6926]

D_total: 4.0035, D_real: 0.3354, D_fake: 0.3601, D_gender: 0.1894, D_age: 7.0085
G_total: 5.3998, G_adv: 2.1866, G_gender: 0.1293, G_age: 6.2195

Epoch 167/300: 100%|██████████| 411/411 [01:02<00:00,  6.62it/s, D_loss=5.2244, G_loss=8.8423]

D_total: 4.0113, D_real: 0.3387, D_fake: 0.3592, D_gender: 0.1870, D_age: 7.0254
G_total: 5.3296, G_adv: 2.1945, G_gender: 0.1313, G_age: 6.0601

Epoch 168/300: 100%|██████████| 411/411 [01:01<00:00,  6.66it/s, D_loss=5.1403, G_loss=9.2259]

D_total: 3.9744, D_real: 0.3288, D_fake: 0.3374, D_gender: 0.1801, D_age: 6.9945
G_total: 5.3123, G_adv: 2.2078, G_gender: 0.1246, G_age: 6.0095

Epoch 169/300: 100%|██████████| 411/411 [01:02<00:00,  6.61it/s, D_loss=3.4847, G_loss=4.2249]

D_total: 4.0511, D_real: 0.3405, D_fake: 0.3620, D_gender: 0.1869, D_age: 7.1007
G_total: 5.3805, G_adv: 2.2014, G_gender: 0.1227, G_age: 6.1617

Epoch 170/300: 100%|██████████| 411/411 [01:09<00:00,  5.90it/s, D_loss=3.7292, G_loss=6.2116]

D_total: 4.0707, D_real: 0.3485, D_fake: 0.3654, D_gender: 0.1894, D_age: 7.1244
G_total: 5.3314, G_adv: 2.1743, G_gender: 0.1343, G_age: 6.0993
Saved checkpoint at epoch 170 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_170.pth

Epoch 171/300: 100%|██████████| 411/411 [01:05<00:00,  6.29it/s, D_loss=5.4568, G_loss=10.7249]

D_total: 3.9822, D_real: 0.3298, D_fake: 0.3442, D_gender: 0.1958, D_age: 6.9773
G_total: 5.2602, G_adv: 2.1444, G_gender: 0.1398, G_age: 6.0079

Epoch 172/300: 100%|██████████| 411/411 [01:04<00:00,  6.40it/s, D_loss=3.7110, G_loss=9.0334]

D_total: 3.9534, D_real: 0.3146, D_fake: 0.3301, D_gender: 0.1778, D_age: 6.9777
G_total: 5.3523, G_adv: 2.2072, G_gender: 0.1193, G_age: 6.0993

Epoch 173/300: 100%|██████████| 411/411 [01:05<00:00,  6.31it/s, D_loss=4.2657, G_loss=3.9644]

D_total: 3.9678, D_real: 0.3177, D_fake: 0.3368, D_gender: 0.1838, D_age: 6.9870
G_total: 5.2584, G_adv: 2.2047, G_gender: 0.1274, G_age: 5.9035

Epoch 174/300: 100%|██████████| 411/411 [01:05<00:00,  6.28it/s, D_loss=5.3872, G_loss=8.8178]

D_total: 4.0105, D_real: 0.3294, D_fake: 0.3533, D_gender: 0.1803, D_age: 7.0499
G_total: 5.3534, G_adv: 2.1876, G_gender: 0.1193, G_age: 6.1408

Epoch 175/300: 100%|██████████| 411/411 [01:11<00:00,  5.78it/s, D_loss=3.3712, G_loss=8.1823]

D_total: 4.0256, D_real: 0.3285, D_fake: 0.3527, D_gender: 0.1851, D_age: 7.0739
G_total: 5.3752, G_adv: 2.2388, G_gender: 0.1312, G_age: 6.0628
Saved checkpoint at epoch 175 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_175.pth

Epoch 176/300: 100%|██████████| 411/411 [01:04<00:00,  6.34it/s, D_loss=5.1082, G_loss=6.5506]

D_total: 3.9081, D_real: 0.3241, D_fake: 0.3355, D_gender: 0.1804, D_age: 6.8679
G_total: 5.2971, G_adv: 2.2367, G_gender: 0.1195, G_age: 5.9295

Epoch 177/300: 100%|██████████| 411/411 [01:05<00:00,  6.27it/s, D_loss=3.0229, G_loss=6.5860]

D_total: 4.0435, D_real: 0.3392, D_fake: 0.3730, D_gender: 0.1819, D_age: 7.0839
G_total: 5.3491, G_adv: 2.1775, G_gender: 0.1248, G_age: 6.1434

Epoch 178/300: 100%|██████████| 411/411 [01:06<00:00,  6.14it/s, D_loss=5.2743, G_loss=5.7690]

D_total: 4.0938, D_real: 0.3451, D_fake: 0.3654, D_gender: 0.1784, D_age: 7.1917
G_total: 5.3821, G_adv: 2.1544, G_gender: 0.1208, G_age: 6.2623

Epoch 179/300: 100%|██████████| 411/411 [01:03<00:00,  6.47it/s, D_loss=3.3515, G_loss=8.4332]

D_total: 4.0379, D_real: 0.3432, D_fake: 0.3574, D_gender: 0.1781, D_age: 7.0902
G_total: 5.3899, G_adv: 2.1967, G_gender: 0.1184, G_age: 6.1970

Epoch 180/300: 100%|██████████| 411/411 [01:08<00:00,  5.96it/s, D_loss=4.0148, G_loss=4.9180]

D_total: 4.0019, D_real: 0.3206, D_fake: 0.3395, D_gender: 0.1747, D_age: 7.0641
G_total: 5.3538, G_adv: 2.1870, G_gender: 0.1128, G_age: 6.1531
Saved checkpoint at epoch 180 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_180.pth

Epoch 181/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=1.9792, G_loss=8.0912]

D_total: 4.0071, D_real: 0.3350, D_fake: 0.3485, D_gender: 0.1797, D_age: 7.0433
G_total: 5.3991, G_adv: 2.2067, G_gender: 0.1190, G_age: 6.1944

Epoch 182/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=3.9279, G_loss=5.4270]

D_total: 4.0068, D_real: 0.3334, D_fake: 0.3401, D_gender: 0.1802, D_age: 7.0517
G_total: 5.3850, G_adv: 2.1886, G_gender: 0.1264, G_age: 6.1907

Epoch 183/300: 100%|██████████| 411/411 [01:04<00:00,  6.37it/s, D_loss=5.2328, G_loss=5.5335]

D_total: 3.9725, D_real: 0.3274, D_fake: 0.3541, D_gender: 0.1866, D_age: 6.9650
G_total: 5.4221, G_adv: 2.2745, G_gender: 0.1293, G_age: 6.0883

Epoch 184/300: 100%|██████████| 411/411 [00:58<00:00,  7.06it/s, D_loss=3.6453, G_loss=6.0217]

D_total: 4.1282, D_real: 0.3662, D_fake: 0.3740, D_gender: 0.1847, D_age: 7.2208
G_total: 5.4487, G_adv: 2.1672, G_gender: 0.1250, G_age: 6.3631

Epoch 185/300: 100%|██████████| 411/411 [01:06<00:00,  6.18it/s, D_loss=2.4186, G_loss=3.8216]

D_total: 4.0862, D_real: 0.3500, D_fake: 0.3607, D_gender: 0.1787, D_age: 7.1757
G_total: 5.4328, G_adv: 2.1608, G_gender: 0.1251, G_age: 6.3439
Saved checkpoint at epoch 185 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_185.pth

Epoch 186/300: 100%|██████████| 411/411 [01:04<00:00,  6.35it/s, D_loss=6.8730, G_loss=6.9609]

D_total: 4.0532, D_real: 0.3492, D_fake: 0.3538, D_gender: 0.1864, D_age: 7.1050
G_total: 5.3443, G_adv: 2.1617, G_gender: 0.1313, G_age: 6.1551

Epoch 187/300: 100%|██████████| 411/411 [01:07<00:00,  6.08it/s, D_loss=5.2828, G_loss=7.7121]

D_total: 4.0297, D_real: 0.3469, D_fake: 0.3544, D_gender: 0.1792, D_age: 7.0715
G_total: 5.4096, G_adv: 2.1384, G_gender: 0.1231, G_age: 6.3454

Epoch 188/300: 100%|██████████| 411/411 [01:05<00:00,  6.30it/s, D_loss=2.9757, G_loss=7.8682]

D_total: 3.9873, D_real: 0.3170, D_fake: 0.3436, D_gender: 0.1823, D_age: 7.0224
G_total: 5.3571, G_adv: 2.2038, G_gender: 0.1317, G_age: 6.0959

Epoch 189/300: 100%|██████████| 411/411 [01:02<00:00,  6.54it/s, D_loss=4.4941, G_loss=9.2118]

D_total: 3.9940, D_real: 0.3363, D_fake: 0.3532, D_gender: 0.1857, D_age: 7.0016
G_total: 5.3040, G_adv: 2.1717, G_gender: 0.1283, G_age: 6.0592

Epoch 190/300: 100%|██████████| 411/411 [01:10<00:00,  5.87it/s, D_loss=7.0515, G_loss=8.0555]

D_total: 3.9896, D_real: 0.3287, D_fake: 0.3473, D_gender: 0.1807, D_age: 7.0142
G_total: 5.3380, G_adv: 2.1980, G_gender: 0.1247, G_age: 6.0806
Saved checkpoint at epoch 190 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_190.pth

Epoch 191/300: 100%|██████████| 411/411 [01:03<00:00,  6.52it/s, D_loss=12.1072, G_loss=21.0171]

D_total: 4.0404, D_real: 0.3392, D_fake: 0.3623, D_gender: 0.1815, D_age: 7.0888
G_total: 5.4637, G_adv: 2.1945, G_gender: 0.1265, G_age: 6.3361

Epoch 192/300: 100%|██████████| 411/411 [01:03<00:00,  6.49it/s, D_loss=8.3596, G_loss=13.8200]

D_total: 4.0311, D_real: 0.3376, D_fake: 0.3533, D_gender: 0.1814, D_age: 7.0812
G_total: 5.4898, G_adv: 2.2579, G_gender: 0.1241, G_age: 6.2653

Epoch 193/300: 100%|██████████| 411/411 [01:03<00:00,  6.51it/s, D_loss=6.1097, G_loss=3.3335]

D_total: 3.9974, D_real: 0.3351, D_fake: 0.3539, D_gender: 0.1843, D_age: 7.0109
G_total: 5.3027, G_adv: 2.2108, G_gender: 0.1275, G_age: 5.9799

Epoch 194/300: 100%|██████████| 411/411 [01:02<00:00,  6.53it/s, D_loss=5.1117, G_loss=3.2985]

D_total: 4.0350, D_real: 0.3515, D_fake: 0.3756, D_gender: 0.1897, D_age: 7.0392
G_total: 5.3015, G_adv: 2.1650, G_gender: 0.1300, G_age: 6.0650

Epoch 195/300: 100%|██████████| 411/411 [01:11<00:00,  5.76it/s, D_loss=3.9448, G_loss=9.3914]

D_total: 4.0339, D_real: 0.3326, D_fake: 0.3593, D_gender: 0.1753, D_age: 7.0955
G_total: 5.4012, G_adv: 2.1809, G_gender: 0.1142, G_age: 6.2580
Saved checkpoint at epoch 195 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_195.pth

Epoch 196/300: 100%|██████████| 411/411 [01:01<00:00,  6.65it/s, D_loss=3.3705, G_loss=7.3809]

D_total: 4.0220, D_real: 0.3378, D_fake: 0.3578, D_gender: 0.1703, D_age: 7.0759
G_total: 5.3719, G_adv: 2.1975, G_gender: 0.1141, G_age: 6.1662

Epoch 197/300: 100%|██████████| 411/411 [01:04<00:00,  6.39it/s, D_loss=4.8949, G_loss=5.3469]

D_total: 4.0071, D_real: 0.3529, D_fake: 0.3765, D_gender: 0.1710, D_age: 7.0110
G_total: 5.2979, G_adv: 2.1625, G_gender: 0.1159, G_age: 6.0852

Epoch 198/300: 100%|██████████| 411/411 [01:02<00:00,  6.58it/s, D_loss=4.4848, G_loss=4.9047]

D_total: 4.0872, D_real: 0.3397, D_fake: 0.3572, D_gender: 0.1788, D_age: 7.1915
G_total: 5.4114, G_adv: 2.1218, G_gender: 0.1155, G_age: 6.3942

Epoch 199/300: 100%|██████████| 411/411 [00:59<00:00,  6.93it/s, D_loss=6.2256, G_loss=10.2133]

D_total: 4.0254, D_real: 0.3588, D_fake: 0.3678, D_gender: 0.1816, D_age: 7.0336
G_total: 5.3804, G_adv: 2.2016, G_gender: 0.1243, G_age: 6.1587

Epoch 200/300: 100%|██████████| 411/411 [01:08<00:00,  6.02it/s, D_loss=3.1310, G_loss=10.9660]

D_total: 4.0158, D_real: 0.3302, D_fake: 0.3565, D_gender: 0.1767, D_age: 7.0622
G_total: 5.3922, G_adv: 2.1744, G_gender: 0.1179, G_age: 6.2470
Saved checkpoint at epoch 200 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_200.pth

Epoch 201/300: 100%|██████████| 411/411 [01:02<00:00,  6.62it/s, D_loss=4.2745, G_loss=6.0204]

D_total: 4.0292, D_real: 0.3475, D_fake: 0.3693, D_gender: 0.1750, D_age: 7.0616
G_total: 5.3794, G_adv: 2.1436, G_gender: 0.1190, G_age: 6.2811

Epoch 202/300: 100%|██████████| 411/411 [01:02<00:00,  6.53it/s, D_loss=5.7671, G_loss=5.4802]

D_total: 4.0303, D_real: 0.3371, D_fake: 0.3500, D_gender: 0.1742, D_age: 7.0947
G_total: 5.4355, G_adv: 2.1952, G_gender: 0.1212, G_age: 6.2864

Epoch 203/300: 100%|██████████| 411/411 [01:05<00:00,  6.32it/s, D_loss=4.6236, G_loss=9.1189]

D_total: 3.9592, D_real: 0.3208, D_fake: 0.3356, D_gender: 0.1793, D_age: 6.9751
G_total: 5.3432, G_adv: 2.2051, G_gender: 0.1257, G_age: 6.0750

Epoch 204/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=8.7868, G_loss=14.3543]

D_total: 4.1068, D_real: 0.3385, D_fake: 0.3562, D_gender: 0.1766, D_age: 7.2362
G_total: 5.4180, G_adv: 2.2172, G_gender: 0.1192, G_age: 6.2111

Epoch 205/300: 100%|██████████| 411/411 [01:08<00:00,  6.00it/s, D_loss=5.3941, G_loss=5.3788]

D_total: 4.0398, D_real: 0.3457, D_fake: 0.3664, D_gender: 0.1742, D_age: 7.0888
G_total: 5.4232, G_adv: 2.2248, G_gender: 0.1182, G_age: 6.2078
Saved checkpoint at epoch 205 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_205.pth

Epoch 206/300: 100%|██████████| 411/411 [01:01<00:00,  6.63it/s, D_loss=4.7021, G_loss=2.6050]

D_total: 3.9092, D_real: 0.3395, D_fake: 0.3541, D_gender: 0.1631, D_age: 6.8639
G_total: 5.2796, G_adv: 2.1995, G_gender: 0.1104, G_age: 5.9837

Epoch 207/300: 100%|██████████| 411/411 [01:03<00:00,  6.49it/s, D_loss=6.1578, G_loss=6.4797]

D_total: 4.0110, D_real: 0.3531, D_fake: 0.3673, D_gender: 0.1639, D_age: 7.0394
G_total: 5.3466, G_adv: 2.1786, G_gender: 0.1048, G_age: 6.1682

Epoch 208/300: 100%|██████████| 411/411 [01:02<00:00,  6.56it/s, D_loss=5.5090, G_loss=4.1276]

D_total: 3.9388, D_real: 0.3353, D_fake: 0.3498, D_gender: 0.1813, D_age: 6.9024
G_total: 5.3394, G_adv: 2.1983, G_gender: 0.1225, G_age: 6.0861

Epoch 209/300: 100%|██████████| 411/411 [01:03<00:00,  6.43it/s, D_loss=2.6110, G_loss=5.5707]

D_total: 3.9757, D_real: 0.3324, D_fake: 0.3485, D_gender: 0.1710, D_age: 6.9970
G_total: 5.4511, G_adv: 2.2060, G_gender: 0.1177, G_age: 6.3018

Epoch 210/300: 100%|██████████| 411/411 [01:09<00:00,  5.88it/s, D_loss=5.4340, G_loss=6.7501]

D_total: 4.0093, D_real: 0.3303, D_fake: 0.3450, D_gender: 0.1754, D_age: 7.0626
G_total: 5.4296, G_adv: 2.1969, G_gender: 0.1169, G_age: 6.2785
Saved checkpoint at epoch 210 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_210.pth

Epoch 211/300: 100%|██████████| 411/411 [01:02<00:00,  6.58it/s, D_loss=3.5251, G_loss=8.3763]

D_total: 4.0333, D_real: 0.3488, D_fake: 0.3742, D_gender: 0.1724, D_age: 7.0677
G_total: 5.3577, G_adv: 2.1945, G_gender: 0.1185, G_age: 6.1370

Epoch 212/300: 100%|██████████| 411/411 [01:02<00:00,  6.63it/s, D_loss=3.2707, G_loss=11.6695]

D_total: 4.0137, D_real: 0.3439, D_fake: 0.3683, D_gender: 0.1712, D_age: 7.0411
G_total: 5.4056, G_adv: 2.2038, G_gender: 0.1150, G_age: 6.2196

Epoch 213/300: 100%|██████████| 411/411 [01:02<00:00,  6.54it/s, D_loss=5.4373, G_loss=7.1935]

D_total: 4.0610, D_real: 0.3591, D_fake: 0.3704, D_gender: 0.1762, D_age: 7.1106
G_total: 5.4059, G_adv: 2.1954, G_gender: 0.1181, G_age: 6.2322

Epoch 214/300: 100%|██████████| 411/411 [01:02<00:00,  6.59it/s, D_loss=5.2118, G_loss=7.8329]

D_total: 3.8816, D_real: 0.3092, D_fake: 0.3402, D_gender: 0.1603, D_age: 6.8573
G_total: 5.3449, G_adv: 2.2403, G_gender: 0.1073, G_age: 6.0376

Epoch 215/300: 100%|██████████| 411/411 [01:03<00:00,  6.45it/s, D_loss=3.5215, G_loss=5.8442]

D_total: 3.9896, D_real: 0.3449, D_fake: 0.3682, D_gender: 0.1771, D_age: 6.9828
G_total: 5.4107, G_adv: 2.2766, G_gender: 0.1217, G_age: 6.0735
Saved checkpoint at epoch 215 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_215.pth

Epoch 216/300: 100%|██████████| 411/411 [01:04<00:00,  6.38it/s, D_loss=5.8775, G_loss=12.5819]

D_total: 3.9954, D_real: 0.3533, D_fake: 0.3623, D_gender: 0.1801, D_age: 6.9869
G_total: 5.3177, G_adv: 2.1830, G_gender: 0.1199, G_age: 6.0774

Epoch 217/300: 100%|██████████| 411/411 [01:01<00:00,  6.73it/s, D_loss=6.1335, G_loss=9.2366]

D_total: 4.0019, D_real: 0.3432, D_fake: 0.3673, D_gender: 0.1644, D_age: 7.0303
G_total: 5.2912, G_adv: 2.1919, G_gender: 0.1158, G_age: 6.0134

Epoch 218/300: 100%|██████████| 411/411 [00:59<00:00,  6.94it/s, D_loss=8.0793, G_loss=8.2379]

D_total: 3.9827, D_real: 0.3356, D_fake: 0.3484, D_gender: 0.1636, D_age: 7.0195
G_total: 5.4177, G_adv: 2.2438, G_gender: 0.1082, G_age: 6.1747

Epoch 219/300: 100%|██████████| 411/411 [01:06<00:00,  6.16it/s, D_loss=6.3861, G_loss=7.3176]

D_total: 4.0847, D_real: 0.3475, D_fake: 0.3735, D_gender: 0.1685, D_age: 7.1789
G_total: 5.3912, G_adv: 2.2019, G_gender: 0.1124, G_age: 6.1989

Epoch 220/300: 100%|██████████| 411/411 [01:10<00:00,  5.86it/s, D_loss=3.6849, G_loss=5.9906]

D_total: 4.0348, D_real: 0.3447, D_fake: 0.3539, D_gender: 0.1731, D_age: 7.0940
G_total: 5.4350, G_adv: 2.2181, G_gender: 0.1192, G_age: 6.2431
Saved checkpoint at epoch 220 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_220.pth

Epoch 221/300: 100%|██████████| 411/411 [01:05<00:00,  6.27it/s, D_loss=4.8247, G_loss=8.4735]

D_total: 4.0114, D_real: 0.3335, D_fake: 0.3548, D_gender: 0.1716, D_age: 7.0600
G_total: 5.3794, G_adv: 2.2281, G_gender: 0.1228, G_age: 6.1060

Epoch 222/300: 100%|██████████| 411/411 [01:04<00:00,  6.34it/s, D_loss=3.2777, G_loss=6.1690]

D_total: 3.8906, D_real: 0.3417, D_fake: 0.3483, D_gender: 0.1646, D_age: 6.8278
G_total: 5.2717, G_adv: 2.1922, G_gender: 0.1067, G_age: 5.9882

Epoch 223/300: 100%|██████████| 411/411 [01:03<00:00,  6.49it/s, D_loss=2.1261, G_loss=6.7803]

D_total: 3.9105, D_real: 0.3220, D_fake: 0.3357, D_gender: 0.1632, D_age: 6.9020
G_total: 5.4136, G_adv: 2.2397, G_gender: 0.1151, G_age: 6.1637

Epoch 224/300: 100%|██████████| 411/411 [01:04<00:00,  6.38it/s, D_loss=2.3609, G_loss=3.9609]

D_total: 3.9839, D_real: 0.3498, D_fake: 0.3661, D_gender: 0.1870, D_age: 6.9527
G_total: 5.2893, G_adv: 2.1696, G_gender: 0.1365, G_age: 6.0210

Epoch 225/300: 100%|██████████| 411/411 [01:08<00:00,  5.98it/s, D_loss=5.1606, G_loss=6.8885]

D_total: 4.0351, D_real: 0.3609, D_fake: 0.3708, D_gender: 0.1731, D_age: 7.0614
G_total: 5.3434, G_adv: 2.1926, G_gender: 0.1230, G_age: 6.1048
Saved checkpoint at epoch 225 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_225.pth

Epoch 226/300: 100%|██████████| 411/411 [01:03<00:00,  6.46it/s, D_loss=6.7229, G_loss=9.7433]

D_total: 4.0050, D_real: 0.3495, D_fake: 0.3733, D_gender: 0.1699, D_age: 7.0152
G_total: 5.3145, G_adv: 2.1729, G_gender: 0.1156, G_age: 6.0983

Epoch 227/300: 100%|██████████| 411/411 [01:03<00:00,  6.46it/s, D_loss=5.7803, G_loss=5.0618]

D_total: 3.9510, D_real: 0.3396, D_fake: 0.3550, D_gender: 0.1784, D_age: 6.9220
G_total: 5.2707, G_adv: 2.1716, G_gender: 0.1166, G_age: 6.0116

Epoch 228/300: 100%|██████████| 411/411 [01:03<00:00,  6.52it/s, D_loss=4.8143, G_loss=10.9136]

D_total: 4.0805, D_real: 0.3627, D_fake: 0.3856, D_gender: 0.1829, D_age: 7.1200
G_total: 5.4524, G_adv: 2.1741, G_gender: 0.1246, G_age: 6.3573

Epoch 229/300: 100%|██████████| 411/411 [01:03<00:00,  6.47it/s, D_loss=4.2456, G_loss=13.2789]

D_total: 3.9023, D_real: 0.3225, D_fake: 0.3298, D_gender: 0.1701, D_age: 6.8801
G_total: 5.4476, G_adv: 2.2783, G_gender: 0.1134, G_age: 6.1573

Epoch 230/300: 100%|██████████| 411/411 [01:10<00:00,  5.83it/s, D_loss=5.4649, G_loss=3.8943]

D_total: 3.9912, D_real: 0.3429, D_fake: 0.3597, D_gender: 0.1794, D_age: 6.9928
G_total: 5.3862, G_adv: 2.1653, G_gender: 0.1180, G_age: 6.2529
Saved checkpoint at epoch 230 in: GAN/src/CounterSynth/checkpoints/checkpoint_epoch_230.pth

Epoch 231/300: 100%|██████████| 411/411 [01:03<00:00,  6.44it/s, D_loss=5.7356, G_loss=9.9203]

D_total: 3.9804, D_real: 0.3332, D_fake: 0.3488, D_gender: 0.1699, D_age: 7.0070
G_total: 5.4505, G_adv: 2.2460, G_gender: 0.1170, G_age: 6.2218

Epoch 232/300: 100%|██████████| 411/411 [01:05<00:00,  6.27it/s, D_loss=1.7969, G_loss=8.8534]

D_total: 3.9208, D_real: 0.3303, D_fake: 0.3487, D_gender: 0.1613, D_age: 6.9045
G_total: 5.3632, G_adv: 2.2344, G_gender: 0.1112, G_age: 6.0797

Epoch 233/300: 100%|██████████| 411/411 [01:04<00:00,  6.39it/s, D_loss=6.1921, G_loss=12.8616]

D_total: 3.9289, D_real: 0.3379, D_fake: 0.3511, D_gender: 0.1652, D_age: 6.9045
G_total: 5.4015, G_adv: 2.2287, G_gender: 0.1091, G_age: 6.1710

Epoch 234/300:  49%|████▉     | 202/411 [00:32<00:31,  6.66it/s, D_loss=6.8772, G_loss=6.1834]

In [ ]:
def generate_brain_images(generator, age, gender, latent_dim=100, num_samples=5):
    """
    Tạo ảnh não dựa trên tuổi và giới tính
    
    Args:
        generator: Generator đã huấn luyện
        age: Tuổi (số thực)
        gender: Giới tính ('m' hoặc 'f')
        latent_dim: Kích thước latent vector
        num_samples: Số lượng mẫu cần tạo
    """
    generator.eval()
    with torch.no_grad():
        # Tạo nhiễu ngẫu nhiên
        z = torch.randn(num_samples, latent_dim, device=device)
        
        # Chuẩn bị điều kiện
        norm_age = age / 100.0  # Chuẩn hóa tuổi
        gender_val = 1.0 if gender == 'm' else 0.0
        condition = torch.tensor([[norm_age, gender_val]]).float().to(device)
        condition = condition.repeat(num_samples, 1)
        
        # Tạo ảnh
        generated_images = generator(z, condition)
        
        # Hiển thị kết quả
        fig, axes = plt.subplots(num_samples, 3, figsize=(15, 5*num_samples))
        
        for i in range(num_samples):
            for j, slice_name in enumerate(['Axial', 'Coronal', 'Sagittal']):
                if num_samples > 1:
                    ax = axes[i, j]
                else:
                    ax = axes[j]
                
                # Chuyển từ [-1, 1] về [0, 1] để hiển thị
                img = (generated_images[i, j].cpu().numpy() + 1) / 2
                ax.imshow(img, cmap='gray')
                ax.set_title(f"{slice_name} Slice")
                ax.axis('off')
        
        gender_str = "Nam" if gender == 'm' else "Nữ"
        plt.suptitle(f'Ảnh MRI não được tạo: Tuổi {age}, Giới tính {gender_str}')
        plt.tight_layout()
        plt.show()

# Thử nghiệm tạo ảnh
try:
    # Tải model đã huấn luyện (nếu có)
    checkpoint_path = 'model_checkpoint_epoch_99.pth'  # Đổi tên file nếu cần
    
    if os.path.exists(checkpoint_path):
        checkpoint = torch.load(checkpoint_path)
        generator.load_state_dict(checkpoint['generator'])
        print("Đã tải model đã huấn luyện!")
    
    # Tạo một số ảnh với các tham số khác nhau
    print("Tạo ảnh cho nam 35 tuổi:")
    generate_brain_images(generator, age=35, gender='m', num_samples=3)
    
    print("Tạo ảnh cho nữ 70 tuổi:")
    generate_brain_images(generator, age=70, gender='f', num_samples=3)
    
except Exception as e:
    print(f"Lỗi khi tạo ảnh: {e}")
    print("Bạn cần huấn luyện mô hình trước khi tạo ảnh.")

In [ ]:
def save_model(generator, discriminator, optimizer_G, optimizer_D, epoch, filename='gan_model.pth'):
    """Lưu trạng thái mô hình GAN"""
    torch.save({
        'generator': generator.state_dict(),
        'discriminator': discriminator.state_dict(),
        'optimizer_G': optimizer_G.state_dict(),
        'optimizer_D': optimizer_D.state_dict(),
        'epoch': epoch
    }, filename)
    print(f"Đã lưu mô hình vào {filename}")

def load_model(generator, discriminator, optimizer_G=None, optimizer_D=None, filename='gan_model.pth'):
    """Tải trạng thái mô hình GAN"""
    if os.path.exists(filename):
        checkpoint = torch.load(filename)
        generator.load_state_dict(checkpoint['generator'])
        discriminator.load_state_dict(checkpoint['discriminator'])
        
        if optimizer_G is not None:
            optimizer_G.load_state_dict(checkpoint['optimizer_G'])
        if optimizer_D is not None:
            optimizer_D.load_state_dict(checkpoint['optimizer_D'])
            
        epoch = checkpoint['epoch']
        print(f"Đã tải mô hình từ epoch {epoch}")
        return epoch
    else:
        print(f"Không tìm thấy file {filename}")
        return 0

# Ví dụ cách sử dụng
try:
    # Khởi tạo optimizer mới (chỉ để minh họa)
    optimizer_G = optim.Adam(generator.parameters(), lr=lr_g, betas=(0.5, 0.999))
    optimizer_D = optim.Adam(discriminator.parameters(), lr=lr_d, betas=(0.5, 0.999))
    
    # Lưu mô hình
    save_model(generator, discriminator, optimizer_G, optimizer_D, num_epochs, 'gan_model_final.pth')
    
    # Tải mô hình (chỉ để minh họa)
    start_epoch = load_model(generator, discriminator, optimizer_G, optimizer_D, 'gan_model_final.pth')
    print(f"Tiếp tục huấn luyện từ epoch {start_epoch}")
    
except Exception as e:
    print(f"Lỗi khi lưu/tải mô hình: {e}")